package tsGenerator

import (
	"os"
	"strings"

	"github.com/ALiwoto/ssg/ssg"
	"github.com/ALiwoto/ssg/ssg/caseUtils"
	gen "github.com/ccl-lang/ccl/src/cclGenerators"
	gValues "github.com/ccl-lang/ccl/src/core/globalValues"
	"github.com/ccl-lang/ccl/src/inputLangs/cclInput/cclErrors"
	"github.com/ccl-lang/ccl/src/inputLangs/cclInput/cclUtils/codeBuilder"
	"github.com/ccl-lang/ccl/src/inputLangs/cclInput/cclValues"
)

func (c *TypeScriptGenerationContext) generateCode() (*gen.CodeGenerationResult, error) {
	c.IsSingleFile, c.SingleFileName = c.IsSingleFileMode(CurrentLanguage)

	if c.IsSingleFile {
		if c.SingleFileName == "" {
			c.SingleFileName = DefaultSingleFileName
		}

		c.SingleFileBuilder = codeBuilder.NewCodeBuilderWithOptions(&codeBuilder.CodeBuilderOptions{
			IndentationStr:  "\t",
			NewLineStr:      "\n",
			EnableDebugInfo: c.Options.GenerateDebugInfo,
		})
		c.SingleFileBuilder.BeginSection(codeBuilder.SectionCommentHeaders)
		c.SingleFileBuilder.AddCommentHeader("// THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.")
		c.SingleFileBuilder.EndSection()
	}

	// Generate each model class
	for _, typeDef := range c.GetGenerationTypeDefinitions() {
		if typeDef.IsCustomModel() {
			err := c.generateCodeForModel(typeDef.GetModelDefinition())
			if err != nil {
				return nil, err
			}
		} else if typeDef.IsCustomEnum() {
			enumDef := typeDef.GetEnumDefinition()
			if enumDef.IsNested() {
				continue
			}
			if err := c.generateCodeForEnum(enumDef); err != nil {
				return nil, err
			}
		} else {
			return nil, &cclErrors.UnsupportedTypeDefinitionError{
				TypeName:       typeDef.GetFullName(),
				TargetLanguage: CurrentLanguage.String(),
			}
		}
	}

	result := &gen.CodeGenerationResult{
		SourceLanguage: gValues.LanguageCCL.String(),
		TargetLanguage: CurrentLanguage.String(),
		OutputFiles:    []string{},
	}

	if c.IsSingleFile {
		path := c.Options.OutputPath + string(os.PathSeparator) + c.SingleFileName
		err := c.WriteCodeFile(path, c.SingleFileBuilder.Build(nil))
		if err != nil {
			return nil, err
		}
		result.OutputFiles = append(result.OutputFiles, path)
	} else {
		for modelName, builder := range c.ModelClasses {
			path := c.Options.OutputPath + string(os.PathSeparator) + modelName + ".ts"
			err := c.WriteCodeFile(path, builder.Build(nil))
			if err != nil {
				return nil, err
			}
			result.OutputFiles = append(result.OutputFiles, path)
		}
	}

	return result, nil
}

func (c *TypeScriptGenerationContext) generateCodeForEnum(enumDef *CCLEnum) error {
	var builder *codeBuilder.CodeBuilder
	if c.IsSingleFile {
		builder = c.SingleFileBuilder
	} else {
		builder = codeBuilder.NewCodeBuilderWithOptions(&codeBuilder.CodeBuilderOptions{
			IndentationStr:  "\t",
			NewLineStr:      "\n",
			EnableDebugInfo: c.Options.GenerateDebugInfo,
		})
		c.ModelClasses[enumDef.Name] = builder
	}

	builder.BeginSection(enumDef.GetFullName())
	defer builder.EndSection()

	if !c.IsSingleFile {
		builder.AddCommentHeader("// THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.")
	}

	return c.generateEnumDeclaration(builder, enumDef)
}

func (c *TypeScriptGenerationContext) generateCodeForModel(model *CCLModel) error {
	var builder *codeBuilder.CodeBuilder
	if c.IsSingleFile {
		builder = c.SingleFileBuilder
	} else {
		builder = codeBuilder.NewCodeBuilderWithOptions(&codeBuilder.CodeBuilderOptions{
			IndentationStr:  "\t",
			NewLineStr:      "\n",
			EnableDebugInfo: c.Options.GenerateDebugInfo,
		})
		c.ModelClasses[model.Name] = builder
	}

	builder.BeginSection(model.GetFullName())
	defer builder.EndSection()

	if !c.IsSingleFile {
		builder.AddCommentHeader("// THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.")
	}

	// In multi-file mode, we need to import other models if they are referenced.
	if !c.IsSingleFile {
		for _, field := range model.Fields {
			targetType := field.Type
			if targetType.IsArray() {
				targetType = targetType.GetUnderlyingType()
			}
			if targetType.IsCustomTypeModel() {
				// Import the custom type
				// Assuming same directory for now
				builder.DoImport(targetType.GetName(), "import { "+targetType.GetName()+" } from './"+targetType.GetName()+"';")
			} else if targetType.IsCustomTypeEnum() {
				enumDef := targetType.GetDefinition().GetEnumDefinition()
				if enumDef.IsNested() {
					if enumDef.OwnedBy != nil && enumDef.OwnedBy != model {
						builder.DoImport(
							enumDef.OwnedBy.Name,
							"import { "+enumDef.OwnedBy.Name+" } from './"+enumDef.OwnedBy.Name+"';",
						)
					}
				} else {
					enumTypeName, err := c.getTypeScriptEnumLocalTypeName(enumDef)
					if err != nil {
						return err
					}
					builder.DoImport(enumDef.GetFullName(), "import { "+enumTypeName+" } from './"+enumDef.Name+"';")
				}
			}
		}
	}

	err := c.generateModelClass(builder, model)
	if err != nil {
		return err
	}

	return nil
}

func (c *TypeScriptGenerationContext) generateModelClass(builder *codeBuilder.CodeBuilder, model *CCLModel) error {
	modelIdConstName := "MODEL_ID_" + strings.ToUpper(caseUtils.ToSnakeCase(model.Name))
	builder.MapVarPairs(
		"model", model.Name,
		"modelIdConst", modelIdConstName,
		"modelId", ssg.ToBase10(model.ModelId),
	)
	defer builder.UnmapVar(
		"model",
		"modelIdConst",
		"modelId",
	)

	builder.LineD("export class $model {").
		Indent()

	// Write model ID constant
	builder.LineD("public static readonly $modelIdConst = $modelId;").
		NewLine()

	// Fields
	for _, field := range model.Fields {
		tsType, err := c.getTypeScriptType(field)
		if err != nil {
			return err
		}
		fieldName := caseUtils.ToCamelCase(field.Name)
		if field.IsNullable() {
			tsType = tsType + " | null"
		}
		builder.MapVarPairs(
			"field", fieldName,
			"type", tsType,
		)
		builder.LineD("public $field: $type;")
		builder.UnmapVar(
			"field",
			"type",
		)
	}
	builder.NewLine()

	// Constructor
	builder.WriteLine("constructor() {").
		Indent()
	for _, field := range model.Fields {
		fieldName := caseUtils.ToCamelCase(field.Name)
		defaultValue := "null"
		if field.IsArray() {
			defaultValue = "[]"
		} else if field.HasDefaultValue() {
			defaultValue = typeScriptDefaultLiteral(field.GetDefaultValue())
			if enumRef := c.GetEnumDefaultReference(field); enumRef != nil {
				ref, err := c.getTypeScriptEnumReference(enumRef.Enum, enumRef.Member)
				if err != nil {
					return err
				}
				defaultValue = ref
			}
		} else {
			switch field.Type.GetName() {
			case cclValues.TypeNameString:
				defaultValue = "\"\""
			case cclValues.TypeNameInt, cclValues.TypeNameInt8, cclValues.TypeNameInt16, cclValues.TypeNameInt32, cclValues.TypeNameInt64,
				cclValues.TypeNameUint, cclValues.TypeNameUint8, cclValues.TypeNameUint16, cclValues.TypeNameUint32, cclValues.TypeNameUint64,
				cclValues.TypeNameFloat, cclValues.TypeNameFloat32, cclValues.TypeNameFloat64, cclValues.TypeNameDateTime:
				defaultValue = "0"
			case cclValues.TypeNameBool:
				defaultValue = "false"
			case cclValues.TypeNameBytes:
				defaultValue = "new Uint8Array(0)"
			default:
				if field.Type.IsCustomTypeEnum() {
					defaultValue = "0"
				} else if field.Type.IsCustomTypeModel() {
					defaultValue = "null" // or new CustomType() if we want non-nullable
				}
			}
		}

		// If it's a custom type and not an array, we might want to allow null or initialize it.
		// For now, let's strictly follow the type. If it's a class, it can be null or undefined in TS if not strict.
		// But let's initialize primitives.
		builder.MapVarPairs(
			"defaultValue", defaultValue,
			"field", fieldName,
		)
		if defaultValue != "null" {
			builder.LineD("this.$field = $defaultValue;")
		} else {
			// For custom types, we might want to leave it undefined or null.
			// If strictNullChecks is on, we need to handle this.
			// Let's assume we initialize to null and the type allows it or we use ! assertion.
			// Actually, better to just not initialize if it's optional, or initialize to null.
			// Let's initialize to null and cast if needed, or just leave it.
			// Let's set it to null for now.
			builder.LineD("this.$field = null as any;")
		}
		builder.UnmapVar(
			"defaultValue",
			"field",
		)
	}
	builder.Unindent().
		WriteLine("}").
		NewLine()

	// Get Model ID
	builder.WriteLine("public getModelId(): number {").
		Indent().
		LineD("return $model.$modelIdConst;").
		Unindent().
		WriteLine("}").
		NewLine()

	// Clone Empty
	builder.LineD("public cloneEmpty(): $model {").
		Indent().
		LineD("return new $model();").
		Unindent().
		WriteLine("}").
		NewLine()

	if err := c.generateDeepCloneMethod(model, builder); err != nil {
		return err
	}

	// Binary Serialization
	if c.NeedsBinarySerialization(CurrentLanguage, model) {
		if err := c.generateSerializeBinaryMethod(model, builder); err != nil {
			return err
		}
		if err := c.generateDeserializeBinaryMethod(model, builder); err != nil {
			return err
		}
	}
	if c.NeedsJsonSerialization(CurrentLanguage, model) {
		if err := c.generateSerializeJsonMethods(model, builder); err != nil {
			return err
		}
	}

	builder.Unindent().
		WriteLine("}")

	if len(model.Enums) > 0 {
		builder.NewLine()
		if err := c.generateNestedEnumNamespace(builder, model); err != nil {
			return err
		}
	}

	return nil
}

//---------------------------------------------------------

func (c *TypeScriptGenerationContext) getTypeScriptType(field *CCLField) (string, error) {
	targetType := field.Type
	if targetType.IsArray() {
		targetType = targetType.GetUnderlyingType()
	}

	tsType := ""
	switch targetType.GetName() {
	case cclValues.TypeNameString:
		tsType = "string"
	case cclValues.TypeNameInt, cclValues.TypeNameInt8, cclValues.TypeNameInt16, cclValues.TypeNameInt32, cclValues.TypeNameInt64,
		cclValues.TypeNameUint, cclValues.TypeNameUint8, cclValues.TypeNameUint16, cclValues.TypeNameUint32, cclValues.TypeNameUint64,
		cclValues.TypeNameFloat, cclValues.TypeNameFloat32, cclValues.TypeNameFloat64:
		tsType = "number"
	case cclValues.TypeNameBool:
		tsType = "boolean"
	case cclValues.TypeNameBytes:
		tsType = "Uint8Array"
	case cclValues.TypeNameDateTime:
		tsType = "number" // Using timestamp
	default:
		if targetType.IsCustomTypeEnum() {
			enumTypeName, err := c.getTypeScriptEnumTypeName(targetType.GetDefinition().GetEnumDefinition())
			if err != nil {
				return "", err
			}
			tsType = enumTypeName
		} else if targetType.IsCustomTypeModel() {
			tsType = targetType.GetName()
		} else {
			tsType = "any"
		}
	}

	if field.IsArray() {
		if targetType.IsCustomTypeModel() {
			tsType = "Array<" + tsType + " | null>"
		} else {
			tsType = tsType + "[]"
		}
	}

	return tsType, nil
}
