package gdGenerator

import (
	"errors"
	"os"
	"strings"

	"github.com/ALiwoto/ssg/ssg"
	"github.com/ccl-lang/ccl/src/core/cclErrors"
	"github.com/ccl-lang/ccl/src/core/cclUtils/codeBuilder"
	"github.com/ccl-lang/ccl/src/core/cclValues"
	"github.com/ccl-lang/ccl/src/core/globalValues"
)

func (c *GDScriptGenerationContext) GenerateCode() error {
	c.ModelClasses = make(map[string]*codeBuilder.CodeBuilder)

	// Generate each model class
	for i := range c.Options.CCLDefinition.TypeDefinitions {
		typeDef := c.Options.CCLDefinition.TypeDefinitions[i]
		if typeDef.IsCustomModel() {
			err := c.generateCodeForMode(typeDef.GetModelDefinition())
			if err != nil {
				return err
			}
		} else {
			// for now, we only support model types
			return &cclErrors.UnsupportedTypeDefinitionError{
				TypeName:       typeDef.GetFullName(),
				TargetLanguage: LanguageName,
			}
		}
	}

	return nil
}

func (c *GDScriptGenerationContext) generateCodeForMode(model *CCLModel) error {
	err := c.GenerateModelClass(model)
	if err != nil {
		return err
	}

	// Get the builder for this model
	builder := c.ModelClasses[model.Name]
	if builder == nil {
		return errors.New("GenerateCode: Unexpected error: model class builder not found after generation")
	}

	// Generate methods
	if c.NeedsBinarySerialization(globalValues.LanguageGo, model) {
		if err = c.generateSerializeBinaryMethod(model, builder); err != nil {
			return err
		}

		if err = c.generateDeserializeBinaryMethod(model, builder); err != nil {
			return err
		}
	}

	path := c.Options.OutputPath + string(os.PathSeparator)
	fileName := ToPascalCase(model.Name) + ".gd"
	err = ssg.WriteFileStr(path+fileName, builder.String())
	if err != nil {
		return err
	}

	// to not lack memory, we should delete the builder
	delete(c.ModelClasses, model.Name)
	return nil
}

func (c *GDScriptGenerationContext) GenerateModelClass(model *CCLModel) error {
	builder := codeBuilder.NewCodeBuilder()
	c.ModelClasses[model.Name] = builder

	// Write class header
	// Write class header
	builder.WriteLine("# THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.")
	builder.NewLine()
	builder.WriteLine("class_name " + model.Name)
	builder.NewLine()

	// Write model ID constant
	modelIdConstName := "MODEL_ID_" + strings.ToUpper(ToSnakeCase(model.Name))
	builder.WriteLine("const " + modelIdConstName +
		" = " + ssg.ToBase10(model.ModelId))
	builder.NewLine()

	// Write class variables
	for _, field := range model.Fields {
		varType := c.getGDScriptType(field)
		if varType == "" {
			return &cclErrors.UnsupportedFieldTypeError{
				TypeName:       field.Type.GetName(),
				FieldName:      field.Name,
				ModelName:      field.Name,
				TargetLanguage: LanguageName,
			}
		}
		builder.WriteLine("var " + ToSnakeCase(field.Name) + ": " + varType)
	}
	builder.NewLine()

	// Add get_model_id method
	builder.WriteLine("func get_model_id() -> int:")
	builder.Indent()
	builder.WriteLine("return " + modelIdConstName)
	builder.Unindent()
	builder.NewLine()

	// Add clone_empty method
	builder.WriteLine("func clone_empty() -> " + model.Name + ":")
	builder.Indent()
	builder.WriteLine("return " + model.Name + ".new()")
	builder.Unindent()
	builder.NewLine()

	return nil
}

func (c *GDScriptGenerationContext) IsCustomType(cclType string) bool {
	return c.Options.CCLDefinition.IsCustomType(cclType)
}

func (c *GDScriptGenerationContext) getGDScriptType(field *cclValues.ModelFieldDefinition) string {
	targetType := field.Type
	if targetType.IsArray() {
		targetType = targetType.GetUnderlyingType()
	}

	gdType := CCLTypesToGdTypes[targetType.GetName()]
	if gdType == "" {
		if !c.IsCustomType(targetType.GetName()) {
			return ""
		}

		gdType = targetType.GetName()
	}

	if field.IsArray() {
		gdType = "Array[" + gdType + "]"
	}

	return gdType
}
