package gdGenerator

import (
	"os"
	"strings"

	"github.com/ALiwoto/ssg/ssg"
	"github.com/ccl-lang/ccl/src/core/cclErrors"
	"github.com/ccl-lang/ccl/src/core/cclUtils"
	"github.com/ccl-lang/ccl/src/core/cclUtils/codeBuilder"
	"github.com/ccl-lang/ccl/src/core/cclValues"
	gValues "github.com/ccl-lang/ccl/src/core/globalValues"
)

func (c *GDScriptGenerationContext) GenerateCode() error {
	c.ModelClasses = make(map[string]*codeBuilder.CodeBuilder)
	c.ModelSections = make(map[string][]string)

	// Generate each model class
	for _, typeDef := range c.Options.CCLDefinition.TypeDefinitions {
		if typeDef.IsCustomModel() {
			fullName := typeDef.GetFullName()
			sections := c.ModelSections[fullName]
			if len(sections) == 0 {
				sections = codeBuilder.GetDefaultOrderedSections()
			}
			sections = ssg.AppendUnique(sections, fullName)
			c.ModelSections[fullName] = sections

			err := c.generateCodeForModel(typeDef.GetModelDefinition())
			if err != nil {
				return err
			}
		} else {
			// for now, we only support model types
			return &cclErrors.UnsupportedTypeDefinitionError{
				TypeName:       typeDef.GetFullName(),
				TargetLanguage: CurrentLanguage.String(),
			}
		}
	}

	return nil
}

func (c *GDScriptGenerationContext) generateCodeForModel(model *CCLModel) error {
	modelName := model.GetFullName()
	builder := codeBuilder.NewCodeBuilderWithOptions(&codeBuilder.CodeBuilderOptions{
		IndentationStr:  "\t",
		NewLineStr:      "\n",
		EnableDebugInfo: c.Options.GenerateDebugInfo,
	})
	c.ModelClasses[modelName] = builder

	builder.BeginSection(modelName)
	defer builder.EndSection()

	err := c.generateModelClass(builder, model)
	if err != nil {
		return err
	}

	// Generate methods
	if c.NeedsBinarySerialization(gValues.LanguageGd, model) {
		if err = c.generateSerializeBinaryMethod(model, builder); err != nil {
			return err
		}

		if err = c.generateDeserializeBinaryMethod(model, builder); err != nil {
			return err
		}
	}

	path := c.Options.OutputPath + string(os.PathSeparator)
	fileName, err := c.GetFileNameForModel(
		gValues.LanguageGd,
		model,
		DefaultFileNamingStyle,
		supportedStyles,
	)
	if err != nil {
		return err
	}

	err = c.WriteCodeFile(path+fileName+".gd", builder.Build(c.ModelSections[modelName]))
	if err != nil {
		return err
	}

	// to not lack memory, we should delete the builder
	delete(c.ModelClasses, modelName)
	return nil
}

func (c *GDScriptGenerationContext) generateModelClass(builder *codeBuilder.CodeBuilder, model *CCLModel) error {
	modelName := model.GetFullName()

	// Write class header
	builder.AddCommentHeader("# THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.").
		WriteLine("class_name " + model.Name).
		NewLine()

	// Write model ID constant
	modelIdConstName := "MODEL_ID_" + strings.ToUpper(cclUtils.ToSnakeCase(model.Name))
	builder.WriteLine("const " + modelIdConstName +
		" = " + ssg.ToBase10(model.ModelId)).
		NewLine()

	// Write class variables
	for _, field := range model.Fields {
		varType := c.getGDScriptType(field)
		if varType == "" {
			return &cclErrors.UnsupportedFieldTypeError{
				TypeName:       field.Type.GetName(),
				FieldName:      field.Name,
				ModelName:      modelName,
				TargetLanguage: CurrentLanguage.String(),
			}
		}
		builder.WriteLine("var " + cclUtils.ToSnakeCase(field.Name) + ": " + varType)
	}
	builder.NewLine()

	// Add get_model_id method
	builder.WriteLine("func get_model_id() -> int:").
		Indent().
		WriteLine("return " + modelIdConstName).
		UnindentLine()

	// Add clone_empty method
	builder.WriteLine("func clone_empty() -> " + model.Name + ":").
		Indent().
		WriteLine("return " + model.Name + ".new()").
		UnindentLine()

	return nil
}

func (c *GDScriptGenerationContext) getGDScriptType(field *cclValues.ModelFieldDefinition) string {
	targetType := field.Type
	if targetType.IsArray() {
		targetType = targetType.GetUnderlyingType()
	}

	gdType := CCLTypesToGdTypes[targetType.GetName()]
	if gdType == "" {
		if !targetType.IsCustomTypeModel() {
			return ""
		}

		gdType = targetType.GetName()
	}

	if field.IsArray() {
		gdType = "Array[" + gdType + "]"
	}

	return gdType
}
