package goGenerator

import (
	"errors"
	"os"

	"github.com/ALiwoto/ssg/ssg"
	"github.com/ccl-lang/ccl/src/core/cclErrors"
	"github.com/ccl-lang/ccl/src/core/cclUtils/codeBuilder"
	"github.com/ccl-lang/ccl/src/core/cclValues"
	gValues "github.com/ccl-lang/ccl/src/core/globalValues"
)

//---------------------------------------------------------

func (c *GoGenerationContext) GenerateCode() error {
	if c.Options.PackageName == "" {
		return errors.New("package name is required for Go code generation")
	}

	var err error
	err = c.GenerateConstants()
	if err != nil {
		return err
	}

	err = c.GenerateVars()
	if err != nil {
		return err
	}

	err = c.GenerateTypes()
	if err != nil {
		return err
	}

	err = c.GenerateHelpers()
	if err != nil {
		return err
	}

	err = c.GenerateMethods()
	if err != nil {
		return err
	}

	path := c.Options.OutputPath + string(os.PathSeparator)
	if c.ConstantsCode != nil {
		err = ssg.WriteFileStr(path+ConstantsFileName, c.ConstantsCode.String())
		if err != nil {
			return err
		}
	}

	if c.VarsCode != nil {
		err = ssg.WriteFileStr(path+VarsFileName, c.VarsCode.String())
		if err != nil {
			return err
		}
	}

	if c.TypesCode != nil {
		err = ssg.WriteFileStr(path+TypesFileName, c.TypesCode.String())
		if err != nil {
			return err
		}
	}

	if c.HelpersCode != nil {
		err = ssg.WriteFileStr(path+HelpersFileName, c.HelpersCode.String())
		if err != nil {
			return err
		}
	}

	if c.MethodsCode != nil {
		err = ssg.WriteFileStr(path+MethodsFileName, c.MethodsCode.String())
		if err != nil {
			return err
		}
	}
	return nil
}

//---------------------------------------------------------

func (c *GoGenerationContext) GenerateConstants() error {
	c.ConstantsCode = codeBuilder.NewCodeBuilder()
	c.ConstantsCode.WriteLine("// THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.").
		NewLine().
		WriteLine("package " + c.Options.PackageName).
		NewLine().
		WriteLine("const (").
		Indent()

	for _, currentTypeDef := range c.Options.CCLDefinition.TypeDefinitions {
		if currentTypeDef.IsCustomModel() {
			err := c.generateConstantsForModel(currentTypeDef.GetModelDefinition())
			if err != nil {
				return err
			}
		} else {
			// for now, we only support model type definitions
			return &cclErrors.UnsupportedTypeDefinitionError{
				TypeName:       currentTypeDef.GetFullName(),
				TargetLanguage: LanguageName,
			}
		}
	}

	c.ConstantsCode.Unindent().
		WriteLine(")")
	return nil
}

func (c *GoGenerationContext) generateConstantsForModel(currentModel *CCLModel) error {
	c.ConstantsCode.WriteLine("ModelId" +
		currentModel.Name + " = " + ssg.ToBase10(currentModel.ModelId),
	)
	return nil
}

//---------------------------------------------------------

func (c *GoGenerationContext) GenerateVars() error {
	c.VarsCode = codeBuilder.NewCodeBuilder()
	c.VarsCode.WriteLine("// THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.").
		NewLine().
		WriteLine("package " + c.Options.PackageName).
		NewLine()

	return nil
}

//---------------------------------------------------------

func (c *GoGenerationContext) GenerateTypes() error {
	c.TypesCode = codeBuilder.NewCodeBuilder()
	c.TypesCode.WriteLine("// THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.").
		NewLine().
		WriteLine("package " + c.Options.PackageName).
		NewLine()

	var neededPackageImports = map[string]bool{}
	for _, currentTypeDef := range c.Options.CCLDefinition.TypeDefinitions {
		if currentTypeDef.IsCustomModel() {
			currentModel := currentTypeDef.GetModelDefinition()
			for _, currentField := range currentModel.Fields {
				switch currentField.Type.GetName() {
				case cclValues.TypeNameDateTime:
					if !neededPackageImports["time"] {
						neededPackageImports["time"] = true
					}
				}
			}
		}
	}

	if len(neededPackageImports) > 0 {
		c.TypesCode.WriteLine("import (").
			Indent()
		for packageName := range neededPackageImports {
			c.TypesCode.WriteLine("\"" + packageName + "\"")
		}
		c.TypesCode.Unindent().
			WriteLine(")").
			NewLine()
	}

	// c.TypesCode.WriteString("type Serializable interface {\n")
	// c.TypesCode.WriteString("\tSerializeBinary() ([]byte, error)\n")
	// c.TypesCode.WriteString("\tDeserializeBinary(data []byte) error\n")
	// c.TypesCode.WriteString("\tCloneEmptySerializable() Serializable\n")
	// c.TypesCode.WriteString("}\n\n")

	for _, currentTypeDef := range c.Options.CCLDefinition.TypeDefinitions {
		if currentTypeDef.IsCustomModel() {
			err := c.generateTypesForModel(currentTypeDef.GetModelDefinition())
			if err != nil {
				return err
			}
		} else {
			// for now, we only support model type definitions
			return &cclErrors.UnsupportedTypeDefinitionError{
				TypeName:       currentTypeDef.GetFullName(),
				TargetLanguage: LanguageName,
			}
		}
	}

	return nil
}

func (c *GoGenerationContext) generateTypesForModel(currentModel *CCLModel) error {
	c.TypesCode.WriteLine("type " + currentModel.Name + " struct {").
		Indent()
	for _, currentField := range currentModel.Fields {
		targetType := currentField.Type

		// TODO: we have to check for other stuff in here
		// or maybe just refactor this part to a more clean code
		if targetType.IsArray() {
			targetType = targetType.GetUnderlyingType()
		}

		theGoType, ok := CCLTypesToGoTypes[targetType.GetName()]
		customDefinedType := c.Options.CCLDefinition.GetModelByName(targetType.GetName())
		if !ok {
			if customDefinedType == nil {
				return &cclErrors.UnsupportedFieldTypeError{
					TypeName:       targetType.GetName(),
					FieldName:      currentField.Name,
					ModelName:      currentModel.Name,
					TargetLanguage: LanguageName,
				}
			}

			// TODO: add ways to specify this type being pointer or not
			theGoType = "*" + customDefinedType.Name
		}

		// TODO: handle extra operators here
		if currentField.IsArray() {
			theGoType = "[]" + theGoType
		}
		c.TypesCode.WriteLine(currentField.Name + " " + theGoType)
	}
	c.TypesCode.Unindent().
		WriteLine("}").
		NewLine()
	return nil
}

//---------------------------------------------------------

func (c *GoGenerationContext) GenerateHelpers() error {
	c.HelpersCode = codeBuilder.NewCodeBuilder()
	c.HelpersCode.WriteLine("// THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.").
		NewLine().
		WriteLine("package " + c.Options.PackageName).
		NewLine()

	return nil
}

//---------------------------------------------------------

func (c *GoGenerationContext) GenerateMethods() error {
	c.MethodsCode = codeBuilder.NewCodeBuilder()
	c.MethodsCode.WriteLine("// THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.").
		NewLine().
		WriteLine("package " + c.Options.PackageName).
		NewLine().
		// default imports
		WriteLine("import (").
		Indent().
		WriteLine("\"bytes\"").
		WriteLine("\"encoding/binary\"").
		WriteLine("\"time\"").
		Unindent().
		WriteLine(")").
		NewLine().
		WriteLine("const (").
		Indent().
		WriteLine("_ = time.April").
		WriteLine("_ = bytes.MinRead").
		WriteLine("_ = binary.MaxVarintLen16").
		Unindent().
		WriteLine(")").
		NewLine()

	for _, currentTypeDef := range c.Options.CCLDefinition.TypeDefinitions {
		if currentTypeDef.IsCustomModel() {
			err := c.generateMethodsForModel(currentTypeDef.GetModelDefinition())
			if err != nil {
				return err
			}
		} else {
			// for now, we only support model type definitions
			return &cclErrors.UnsupportedTypeDefinitionError{
				TypeName:       currentTypeDef.GetFullName(),
				TargetLanguage: LanguageName,
			}
		}
	}

	return nil
}

func (c *GoGenerationContext) generateMethodsForModel(currentModel *CCLModel) error {
	c.MethodsCode.NewLine().
		WriteLine("//------------------------------------------------------------").
		NewLine().
		WriteLine("func (m *" + currentModel.Name + ") GetModelId() int {").
		Indent().
		WriteLine("return ModelId" + currentModel.Name).
		Unindent().
		WriteLine("}")

	// generate CloneEmpty() method
	if c.NeedsCloneMethods(gValues.LanguageGo, currentModel) {
		c.generateCloneMethods(currentModel)
	}

	if c.NeedsBinarySerialization(gValues.LanguageGo, currentModel) {
		c.generateSerializeBinaryMethod(currentModel)
		c.generateDeserializeBinaryMethod(currentModel)
	}
	return nil
}

//---------------------------------------------------------
