package goGenerator

import (
	"github.com/ALiwoto/ssg/ssg/caseUtils"
	"github.com/ccl-lang/ccl/src/inputLangs/cclInput/cclUtils/codeBuilder"
	"github.com/ccl-lang/ccl/src/inputLangs/cclInput/cclValues"
)

func (c *GoGenerationContext) generateSerializeJsonMethods(
	builder *codeBuilder.CodeBuilder,
	model *CCLModel,
) error {
	if err := c.generateSerializeJsonMethod(builder, model); err != nil {
		return err
	}
	if err := c.generateDeserializeJsonMethod(builder, model); err != nil {
		return err
	}
	return nil
}

func (c *GoGenerationContext) generateSerializeJsonMethod(
	builder *codeBuilder.CodeBuilder,
	model *CCLModel,
) error {
	// Generated SerializeJSON methods build output with bytes.Buffer.
	registerGoImport(builder, "bytes")
	if len(model.Fields) > 0 {
		// Generated JSON field names and primitive values use strconv formatting helpers.
		registerGoImport(builder, "strconv")
	}

	builder.ExpectMappedVars("model", "modelName")
	builder.LineD("func (m $model) SerializeJSON() (string, error) {").
		Indent().
		WriteLine("if m == nil {").
		Indent().
		WriteLine("return \"null\", nil").
		Unindent().
		WriteLine("}").
		WriteLine("var buf bytes.Buffer").
		WriteLine("buf.WriteByte('{')").
		WriteLine("first := true").
		NewLine()

	for _, field := range model.Fields {
		jsonName, err := c.GetJsonFieldName(CurrentLanguage, model, field)
		if err != nil {
			return err
		}
		builder.WriteLine("if !first {").
			Indent().
			WriteLine("buf.WriteByte(',')").
			Unindent().
			WriteLine("}").
			WriteLine("first = false").
			WriteLine("buf.WriteString(strconv.Quote(\"" + jsonName + "\"))").
			WriteLine("buf.WriteByte(':')")

		if field.IsArray() {
			if err = c.generateArraySerializeJson(builder, field); err != nil {
				return err
			}
		} else if err = c.generateFieldSerializeJson(builder, field); err != nil {
			return err
		}
		builder.NewLine()
	}

	builder.WriteLine("buf.WriteByte('}')").
		WriteLine("return buf.String(), nil").
		Unindent().
		WriteLine("}").
		NewLine()

	return nil
}

func (c *GoGenerationContext) generateDeserializeJsonMethod(
	builder *codeBuilder.CodeBuilder,
	model *CCLModel,
) error {
	// Generated JSON deserialization reads object fields directly with encoding/json.
	registerGoImport(builder, "encoding/json")
	// Generated JSON field readers check null values and parse quoted primitives with strings.TrimSpace.
	registerGoImport(builder, "strings")

	builder.ExpectMappedVars("model")
	builder.LineD("func (m $model) DeserializeJSON(data string) error {").
		Indent().
		WriteLine("if m == nil {").
		Indent().
		WriteLine("return nil").
		Unindent().
		WriteLine("}").
		WriteLine("data = strings.TrimSpace(data)").
		WriteLine("if data == \"\" || data == \"null\" {").
		Indent().
		WriteLine("return nil").
		Unindent().
		WriteLine("}").
		WriteLine("var fields map[string]json.RawMessage").
		WriteLine("if err := json.Unmarshal([]byte(data), &fields); err != nil {").
		Indent().
		WriteLine("return err").
		Unindent().
		WriteLine("}").
		NewLine()

	for _, field := range model.Fields {
		jsonName, err := c.GetJsonFieldName(CurrentLanguage, model, field)
		if err != nil {
			return err
		}
		rawName := lowerGoVarName(field.Name) + "Raw"
		builder.WriteLine(rawName + ", ok := fields[\"" + jsonName + "\"]").
			WriteLine("if ok && strings.TrimSpace(string(" + rawName + ")) != \"null\" {").
			Indent()
		if field.IsArray() {
			if err = c.generateArrayDeserializeJson(builder, field, rawName); err != nil {
				return err
			}
		} else if err = c.generateFieldDeserializeJson(builder, field, rawName); err != nil {
			return err
		}
		builder.Unindent().
			WriteLine("}").
			NewLine()
	}

	builder.WriteLine("return nil").
		Unindent().
		WriteLine("}").
		NewLine()

	return nil
}

func (c *GoGenerationContext) generateFieldSerializeJson(
	builder *codeBuilder.CodeBuilder,
	field *CCLField,
) error {
	fieldName := "m." + field.Name
	switch field.Type.GetName() {
	case cclValues.TypeNameString:
		builder.WriteLine("buf.WriteString(strconv.Quote(" + fieldName + "))")
	case cclValues.TypeNameBool:
		builder.WriteLine("if " + fieldName + " {").
			Indent().
			WriteLine("buf.WriteString(\"true\")").
			Unindent().
			WriteLine("} else {").
			Indent().
			WriteLine("buf.WriteString(\"false\")").
			Unindent().
			WriteLine("}")
	case cclValues.TypeNameBytes:
		// Generated bytes JSON serialization encodes fields with base64.StdEncoding.
		registerGoImport(builder, "encoding/base64")
		builder.WriteLine("buf.WriteString(strconv.Quote(base64.StdEncoding.EncodeToString(" + fieldName + ")))")
	case cclValues.TypeNameDateTime:
		builder.WriteLine("buf.WriteString(strconv.FormatInt(" + fieldName + ".UnixNano(), 10))")
	default:
		if c.isGoJsonSignedInteger(field.Type) {
			builder.WriteLine("buf.WriteString(strconv.FormatInt(int64(" + fieldName + "), 10))")
		} else if c.isGoJsonUnsignedInteger(field.Type) {
			builder.WriteLine("buf.WriteString(strconv.FormatUint(uint64(" + fieldName + "), 10))")
		} else if c.isGoJsonFloat(field.Type) {
			bitSize := "64"
			if field.Type.GetName() == cclValues.TypeNameFloat32 {
				bitSize = "32"
			}
			builder.WriteLine("buf.WriteString(strconv.FormatFloat(float64(" + fieldName + "), 'g', -1, " + bitSize + "))")
		} else if field.IsCustomTypeModel() {
			builder.WriteLine("if " + fieldName + " == nil {").
				Indent().
				WriteLine("buf.WriteString(\"null\")").
				Unindent().
				WriteLine("} else {").
				Indent().
				WriteLine("jsonValue, err := " + fieldName + ".SerializeJSON()").
				WriteLine("if err != nil {").
				Indent().
				WriteLine("return \"\", err").
				Unindent().
				WriteLine("}").
				WriteLine("buf.WriteString(jsonValue)").
				Unindent().
				WriteLine("}")
		} else {
			return c.unsupportedGoJsonField(field)
		}
	}
	return nil
}

func (c *GoGenerationContext) generateArraySerializeJson(
	builder *codeBuilder.CodeBuilder,
	field *CCLField,
) error {
	targetType := field.Type.GetUnderlyingType()
	fieldName := "m." + field.Name
	builder.WriteLine("if " + fieldName + " == nil {").
		Indent().
		WriteLine("buf.WriteString(\"null\")").
		Unindent().
		WriteLine("} else {").
		Indent().
		WriteLine("buf.WriteByte('[')").
		WriteLine("for i, item := range " + fieldName + " {").
		Indent().
		WriteLine("if i > 0 {").
		Indent().
		WriteLine("buf.WriteByte(',')").
		Unindent().
		WriteLine("}")

	switch targetType.GetName() {
	case cclValues.TypeNameString:
		builder.WriteLine("buf.WriteString(strconv.Quote(item))")
	case cclValues.TypeNameBool:
		builder.WriteLine("if item {").
			Indent().
			WriteLine("buf.WriteString(\"true\")").
			Unindent().
			WriteLine("} else {").
			Indent().
			WriteLine("buf.WriteString(\"false\")").
			Unindent().
			WriteLine("}")
	case cclValues.TypeNameBytes:
		// Generated bytes JSON array serialization encodes items with base64.StdEncoding.
		registerGoImport(builder, "encoding/base64")
		builder.WriteLine("buf.WriteString(strconv.Quote(base64.StdEncoding.EncodeToString(item)))")
	case cclValues.TypeNameDateTime:
		builder.WriteLine("buf.WriteString(strconv.FormatInt(item.UnixNano(), 10))")
	default:
		if c.isGoJsonSignedInteger(targetType) {
			builder.WriteLine("buf.WriteString(strconv.FormatInt(int64(item), 10))")
		} else if c.isGoJsonUnsignedInteger(targetType) {
			builder.WriteLine("buf.WriteString(strconv.FormatUint(uint64(item), 10))")
		} else if c.isGoJsonFloat(targetType) {
			bitSize := "64"
			if targetType.GetName() == cclValues.TypeNameFloat32 {
				bitSize = "32"
			}
			builder.WriteLine("buf.WriteString(strconv.FormatFloat(float64(item), 'g', -1, " + bitSize + "))")
		} else if targetType.IsCustomTypeModel() {
			builder.WriteLine("if item == nil {").
				Indent().
				WriteLine("buf.WriteString(\"null\")").
				Unindent().
				WriteLine("} else {").
				Indent().
				WriteLine("jsonValue, err := item.SerializeJSON()").
				WriteLine("if err != nil {").
				Indent().
				WriteLine("return \"\", err").
				Unindent().
				WriteLine("}").
				WriteLine("buf.WriteString(jsonValue)").
				Unindent().
				WriteLine("}")
		} else {
			return c.unsupportedGoJsonField(field)
		}
	}

	builder.Unindent().
		WriteLine("}").
		WriteLine("buf.WriteByte(']')").
		Unindent().
		WriteLine("}")
	return nil
}

func (c *GoGenerationContext) generateFieldDeserializeJson(
	builder *codeBuilder.CodeBuilder,
	field *CCLField,
	rawName string,
) error {
	fieldRawName := field.GetName()
	fieldName := "m." + fieldRawName
	valueName := caseUtils.ToCamelCase(fieldRawName) + "Value"
	switch field.Type.GetName() {
	case cclValues.TypeNameString:
		c.writeGoJsonStringRead(builder, valueName, rawName)
		builder.WriteLine(fieldName + " = " + valueName)
	case cclValues.TypeNameBool:
		c.writeGoJsonBoolRead(builder, valueName, rawName)
		builder.WriteLine(fieldName + " = " + valueName)
	case cclValues.TypeNameBytes:
		c.writeGoJsonBytesRead(builder, valueName, rawName)
		builder.WriteLine(fieldName + " = " + valueName)
	default:
		if c.isGoJsonSignedInteger(field.Type) {
			c.writeGoJsonIntRead(builder, valueName, rawName)
			if field.Type.GetName() == cclValues.TypeNameDateTime {
				// Generated datetime JSON deserialization rebuilds values with time.Unix.
				registerGoImport(builder, "time")
				builder.WriteLine(fieldName + " = time.Unix(0, " + valueName + ")")
			} else {
				castType, err := c.goJsonIntegerCast(field.Type)
				if err != nil {
					return err
				}
				builder.WriteLine(fieldName + " = " + castType + "(" + valueName + ")")
			}
		} else if c.isGoJsonUnsignedInteger(field.Type) {
			c.writeGoJsonUintRead(builder, valueName, rawName)
			castType, err := c.goJsonIntegerCast(field.Type)
			if err != nil {
				return err
			}
			builder.WriteLine(fieldName + " = " + castType + "(" + valueName + ")")
		} else if c.isGoJsonFloat(field.Type) {
			c.writeGoJsonFloatRead(builder, valueName, rawName)
			builder.WriteLine(fieldName + " = " + c.goJsonFloatCast(field.Type) + "(" + valueName + ")")
		} else if field.IsCustomTypeModel() {
			builder.WriteLine(fieldName + " = new(" + field.Type.GetName() + ")").
				WriteLine("if err := " + fieldName + ".DeserializeJSON(string(" + rawName + ")); err != nil {").
				Indent().
				WriteLine("return err").
				Unindent().
				WriteLine("}")
		} else {
			return c.unsupportedGoJsonField(field)
		}
	}
	return nil
}

func (c *GoGenerationContext) generateArrayDeserializeJson(
	builder *codeBuilder.CodeBuilder,
	field *CCLField,
	rawName string,
) error {
	targetType := field.Type.GetUnderlyingType()
	fieldName := "m." + field.Name
	valueName := lowerGoVarName(field.Name) + "Items"
	itemValueName := lowerGoVarName(field.Name) + "ItemValue"
	itemType, err := c.getGoJsonArrayItemType(targetType)
	if err != nil {
		return err
	}
	if itemType == "" {
		return c.unsupportedGoJsonField(field)
	}

	c.writeGoJsonArrayRead(builder, valueName, rawName)
	builder.WriteLine(fieldName + " = make([]" + itemType + ", 0, len(" + valueName + "))").
		WriteLine("for _, item := range " + valueName + " {").
		Indent()

	switch targetType.GetName() {
	case cclValues.TypeNameString:
		c.writeGoJsonStringRead(builder, itemValueName, "item")
	case cclValues.TypeNameBool:
		c.writeGoJsonBoolRead(builder, itemValueName, "item")
	case cclValues.TypeNameBytes:
		c.writeGoJsonBytesRead(builder, itemValueName, "item")
	default:
		if c.isGoJsonSignedInteger(targetType) {
			c.writeGoJsonIntRead(builder, itemValueName, "item")
		} else if c.isGoJsonUnsignedInteger(targetType) {
			c.writeGoJsonUintRead(builder, itemValueName, "item")
		} else if c.isGoJsonFloat(targetType) {
			c.writeGoJsonFloatRead(builder, itemValueName, "item")
		} else if targetType.IsCustomTypeModel() {
			builder.WriteLine("if strings.TrimSpace(string(item)) == \"null\" {").
				Indent().
				WriteLine(fieldName + " = append(" + fieldName + ", nil)").
				WriteLine("continue").
				Unindent().
				WriteLine("}").
				WriteLine(itemValueName + " := new(" + targetType.GetName() + ")").
				WriteLine("err := " + itemValueName + ".DeserializeJSON(string(item))")
			builder.WriteLine("if err != nil {").
				Indent().
				WriteLine("return err").
				Unindent().
				WriteLine("}")
		}
	}

	if targetType.IsCustomTypeModel() || targetType.GetName() == cclValues.TypeNameString ||
		targetType.GetName() == cclValues.TypeNameBool || targetType.GetName() == cclValues.TypeNameBytes {
		builder.WriteLine(fieldName + " = append(" + fieldName + ", " + itemValueName + ")")
	} else if targetType.GetName() == cclValues.TypeNameDateTime {
		// Generated datetime JSON array deserialization rebuilds items with time.Unix.
		registerGoImport(builder, "time")
		builder.WriteLine(fieldName + " = append(" + fieldName + ", time.Unix(0, " + itemValueName + "))")
	} else if c.isGoJsonSignedInteger(targetType) || c.isGoJsonUnsignedInteger(targetType) {
		castType, err := c.goJsonIntegerCast(targetType)
		if err != nil {
			return err
		}
		builder.WriteLine(fieldName + " = append(" + fieldName + ", " + castType + "(" + itemValueName + "))")
	} else if c.isGoJsonFloat(targetType) {
		builder.WriteLine(fieldName + " = append(" + fieldName + ", " + c.goJsonFloatCast(targetType) + "(" + itemValueName + "))")
	}

	builder.Unindent().
		WriteLine("}")
	return nil
}
