package goGenerator

import (
	"errors"
	"os"
	"strings"

	"github.com/ALiwoto/ssg/ssg"
	"github.com/ccl-lang/ccl/src/core/cclErrors"
	"github.com/ccl-lang/ccl/src/core/cclValues"
)

//---------------------------------------------------------

func (c *GoGenerationContext) GenerateCode() error {
	if c.Options.PackageName == "" {
		return errors.New("package name is required for Go code generation")
	}

	var err error
	err = c.GenerateConstants()
	if err != nil {
		return err
	}

	err = c.GenerateVars()
	if err != nil {
		return err
	}

	err = c.GenerateTypes()
	if err != nil {
		return err
	}

	err = c.GenerateHelpers()
	if err != nil {
		return err
	}

	err = c.GenerateMethods()
	if err != nil {
		return err
	}

	path := c.Options.OutputPath + string(os.PathSeparator)
	if c.ConstantsCode != nil {
		err = ssg.WriteFileStr(path+ConstantsFileName, c.ConstantsCode.String())
		if err != nil {
			return err
		}
	}

	if c.VarsCode != nil {
		err = ssg.WriteFileStr(path+VarsFileName, c.VarsCode.String())
		if err != nil {
			return err
		}
	}

	if c.TypesCode != nil {
		err = ssg.WriteFileStr(path+TypesFileName, c.TypesCode.String())
		if err != nil {
			return err
		}
	}

	if c.HelpersCode != nil {
		err = ssg.WriteFileStr(path+HelpersFileName, c.HelpersCode.String())
		if err != nil {
			return err
		}
	}

	if c.MethodsCode != nil {
		err = ssg.WriteFileStr(path+MethodsFileName, c.MethodsCode.String())
		if err != nil {
			return err
		}
	}
	return nil
}

//---------------------------------------------------------

func (c *GoGenerationContext) GenerateConstants() error {
	c.ConstantsCode = &strings.Builder{}
	c.ConstantsCode.WriteString("// THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.\n\n")
	c.ConstantsCode.WriteString("package " + c.Options.PackageName + "\n\n")
	c.ConstantsCode.WriteString("const (\n")

	for _, currentTypeDef := range c.Options.CCLDefinition.TypeDefinitions {
		if currentTypeDef.IsCustomModel() {
			err := c.generateConstantsForModel(currentTypeDef.GetModelDefinition())
			if err != nil {
				return err
			}
		} else {
			// for now, we only support model type definitions
			return &cclErrors.UnsupportedTypeDefinitionError{
				TypeName:       currentTypeDef.GetFullName(),
				TargetLanguage: LanguageName,
			}
		}
	}

	c.ConstantsCode.WriteString(")\n")
	return nil
}

func (c *GoGenerationContext) generateConstantsForModel(currentModel *CCLModel) error {
	c.ConstantsCode.WriteString("\tModelId" +
		currentModel.Name + " = " + ssg.ToBase10(currentModel.ModelId) + "\n",
	)
	return nil
}

//---------------------------------------------------------

func (c *GoGenerationContext) GenerateVars() error {
	c.VarsCode = &strings.Builder{}
	c.VarsCode.WriteString("// THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.\n\n")
	c.VarsCode.WriteString("package " + c.Options.PackageName + "\n\n")

	return nil
}

//---------------------------------------------------------

func (c *GoGenerationContext) GenerateTypes() error {
	c.TypesCode = &strings.Builder{}
	c.TypesCode.WriteString("// THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.\n\n")
	c.TypesCode.WriteString("package " + c.Options.PackageName + "\n\n")

	var neededPackageImports = map[string]bool{}
	for _, currentTypeDef := range c.Options.CCLDefinition.TypeDefinitions {
		if currentTypeDef.IsCustomModel() {
			currentModel := currentTypeDef.GetModelDefinition()
			for _, currentField := range currentModel.Fields {
				switch currentField.Type.GetName() {
				case cclValues.TypeNameDateTime:
					if !neededPackageImports["time"] {
						neededPackageImports["time"] = true
					}
				}
			}
		}
	}

	if len(neededPackageImports) > 0 {
		c.TypesCode.WriteString("import (\n")
		for packageName := range neededPackageImports {
			c.TypesCode.WriteString("\t\"" + packageName + "\"\n")
		}
		c.TypesCode.WriteString(")\n\n")
	}

	// c.TypesCode.WriteString("type Serializable interface {\n")
	// c.TypesCode.WriteString("\tSerializeBinary() ([]byte, error)\n")
	// c.TypesCode.WriteString("\tDeserializeBinary(data []byte) error\n")
	// c.TypesCode.WriteString("\tCloneEmptySerializable() Serializable\n")
	// c.TypesCode.WriteString("}\n\n")

	for _, currentTypeDef := range c.Options.CCLDefinition.TypeDefinitions {
		if currentTypeDef.IsCustomModel() {
			err := c.generateTypesForModel(currentTypeDef.GetModelDefinition())
			if err != nil {
				return err
			}
		} else {
			// for now, we only support model type definitions
			return &cclErrors.UnsupportedTypeDefinitionError{
				TypeName:       currentTypeDef.GetFullName(),
				TargetLanguage: LanguageName,
			}
		}
	}

	return nil
}

func (c *GoGenerationContext) generateTypesForModel(currentModel *CCLModel) error {
	c.TypesCode.WriteString("type " + currentModel.Name + " struct {\n")
	for _, currentField := range currentModel.Fields {
		targetType := currentField.Type

		// TODO: we have to check for other stuff in here
		// or maybe just refactor this part to a more clean code
		if targetType.IsArray() {
			targetType = targetType.GetUnderlyingType()
		}

		theGoType, ok := CCLTypesToGoTypes[targetType.GetName()]
		customDefinedType := c.Options.CCLDefinition.GetModelByName(targetType.GetName())
		if !ok {
			if customDefinedType == nil {
				return &cclErrors.UnsupportedFieldTypeError{
					TypeName:       targetType.GetName(),
					FieldName:      currentField.Name,
					ModelName:      currentModel.Name,
					TargetLanguage: LanguageName,
				}
			}

			// TODO: add ways to specify this type being pointer or not
			theGoType = "*" + customDefinedType.Name
		}

		// TODO: handle extra operators here
		if currentField.IsArray() {
			theGoType = "[]" + theGoType
		}
		c.TypesCode.WriteString("\t" + currentField.Name + " " + theGoType + "\n")
	}
	c.TypesCode.WriteString("}\n\n")
	return nil
}

//---------------------------------------------------------

func (c *GoGenerationContext) GenerateHelpers() error {
	c.HelpersCode = &strings.Builder{}
	c.HelpersCode.WriteString("// THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.\n\n")
	c.HelpersCode.WriteString("package " + c.Options.PackageName + "\n\n")

	return nil
}

//---------------------------------------------------------

func (c *GoGenerationContext) GenerateMethods() error {
	c.MethodsCode = &strings.Builder{}
	c.MethodsCode.WriteString("// THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.\n\n")
	c.MethodsCode.WriteString("package " + c.Options.PackageName + "\n\n")

	// default imports
	c.MethodsCode.WriteString("import (\n")
	c.MethodsCode.WriteString("\t\"bytes\"\n")
	c.MethodsCode.WriteString("\t\"encoding/binary\"\n")
	c.MethodsCode.WriteString("\t\"time\"\n")
	c.MethodsCode.WriteString(")\n\n")
	c.MethodsCode.WriteString("const (\n")
	c.MethodsCode.WriteString("\t_ = time.April\n")
	c.MethodsCode.WriteString("\t_ = bytes.MinRead\n")
	c.MethodsCode.WriteString("\t_ = binary.MaxVarintLen16\n")
	c.MethodsCode.WriteString(")\n\n")

	for _, currentTypeDef := range c.Options.CCLDefinition.TypeDefinitions {
		if currentTypeDef.IsCustomModel() {
			err := c.generateMethodsForModel(currentTypeDef.GetModelDefinition())
			if err != nil {
				return err
			}
		} else {
			// for now, we only support model type definitions
			return &cclErrors.UnsupportedTypeDefinitionError{
				TypeName:       currentTypeDef.GetFullName(),
				TargetLanguage: LanguageName,
			}
		}
	}

	return nil
}

func (c *GoGenerationContext) generateMethodsForModel(currentModel *CCLModel) error {
	c.MethodsCode.WriteString("\n//------------------------------------------------------------\n\n")
	c.MethodsCode.WriteString("func (m *" + currentModel.Name + ") GetModelId() int {\n")
	c.MethodsCode.WriteString("\treturn ModelId" + currentModel.Name + "\n")
	c.MethodsCode.WriteString("}\n")

	// generate CloneEmpty() method
	if c.NeedsCloneMethods(currentModel) {
		c.generateCloneMethods(currentModel)
	}

	if c.NeedsBinarySerialization(currentModel) {
		c.generateSerializeBinaryMethod(currentModel)
		c.generateDeserializeBinaryMethod(currentModel)
	}
	return nil
}

//---------------------------------------------------------
