package rsGenerator

import (
	"path/filepath"
	"sort"

	"github.com/ccl-lang/ccl/src/inputLangs/cclInput/cclUtils/codeBuilder"
)

func (c *RustGenerationContext) getCodeBuilder(relativePath string, section string) *codeBuilder.CodeBuilder {
	if c.CodeByPath == nil {
		c.CodeByPath = map[string]*codeBuilder.CodeBuilder{}
	}

	builder := c.CodeByPath[relativePath]
	if builder != nil {
		return builder
	}

	builder = codeBuilder.NewCodeBuilderWithOptions(&codeBuilder.CodeBuilderOptions{
		IndentationStr:  "    ",
		NewLineStr:      "\n",
		EnableDebugInfo: c.Options.GenerateDebugInfo,
	})
	builder.BeginSection(section)
	builder.AddCommentHeader("// THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.")

	c.CodeByPath[relativePath] = builder
	return builder
}

func (c *RustGenerationContext) finalizeCodeBuilders() {
	for _, builder := range c.CodeByPath {
		builder.EndSection()
	}
}

func (c *RustGenerationContext) writeCodeBuilders() ([]string, error) {
	relativePaths := make([]string, 0, len(c.CodeByPath))
	for relativePath := range c.CodeByPath {
		relativePaths = append(relativePaths, relativePath)
	}
	sort.Strings(relativePaths)

	outputFiles := make([]string, 0, len(relativePaths))
	for _, relativePath := range relativePaths {
		builder := c.CodeByPath[relativePath]
		fullPath := filepath.Join(c.Options.OutputPath, relativePath)
		if err := c.WriteCodeFile(fullPath, builder.Build(nil)); err != nil {
			return nil, err
		}
		outputFiles = append(outputFiles, fullPath)
	}

	return outputFiles, nil
}
