package csGenerator

import (
	"os"

	"github.com/ALiwoto/ssg/ssg"
	gen "github.com/ccl-lang/ccl/src/cclGenerators"
	"github.com/ccl-lang/ccl/src/core/cclErrors"
	"github.com/ccl-lang/ccl/src/core/cclUtils"
	"github.com/ccl-lang/ccl/src/core/cclUtils/codeBuilder"
	"github.com/ccl-lang/ccl/src/core/cclValues"
	gValues "github.com/ccl-lang/ccl/src/core/globalValues"
)

func (c *CSharpGenerationContext) generateCode() (*gen.CodeGenerationResult, error) {
	c.IsSingleFile, c.SingleFileName = c.IsSingleFileMode(CurrentLanguage)
	c.CSharpNamespace = c.getNamespace()

	if c.IsSingleFile {
		if c.SingleFileName == "" {
			c.SingleFileName = DefaultSingleFileName
		}

		c.SingleFileBuilder = codeBuilder.NewCodeBuilderWithOptions(&codeBuilder.CodeBuilderOptions{
			IndentationStr:  "    ",
			NewLineStr:      "\n",
			EnableDebugInfo: c.Options.GenerateDebugInfo,
		})
		c.SingleFileBuilder.BeginSection(codeBuilder.SectionCommentHeaders)
		c.SingleFileBuilder.AddCommentHeader("// THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.")
		c.SingleFileBuilder.EndSection()

		c.SingleFileBuilder.WriteLine("using System;")
		c.SingleFileBuilder.WriteLine("using System.Collections.Generic;")
		c.SingleFileBuilder.WriteLine("using System.IO;")
		c.SingleFileBuilder.WriteLine("using System.Text;")
		c.SingleFileBuilder.NewLine()
		c.SingleFileBuilder.WriteLine("namespace " + c.CSharpNamespace)
		c.SingleFileBuilder.WriteLine("{")
		c.SingleFileBuilder.Indent()
	}

	// Generate each model class
	for _, typeDef := range c.Options.CCLDefinition.TypeDefinitions {
		if typeDef.IsCustomModel() {
			err := c.generateCodeForModel(typeDef.GetModelDefinition())
			if err != nil {
				return nil, err
			}
		} else {
			// for now, we only support model types
			return nil, &cclErrors.UnsupportedTypeDefinitionError{
				TypeName:       typeDef.GetFullName(),
				TargetLanguage: CurrentLanguage.String(),
			}
		}
	}

	if c.IsSingleFile {
		c.SingleFileBuilder.Unindent()
		c.SingleFileBuilder.WriteLine("}")
	}

	result := &gen.CodeGenerationResult{
		SourceLanguage: gValues.LanguageCCL.String(),
		TargetLanguage: CurrentLanguage.String(),
		OutputFiles:    []string{},
	}

	if c.IsSingleFile {
		path := c.Options.OutputPath + string(os.PathSeparator) + c.SingleFileName
		err := c.WriteCodeFile(path, c.SingleFileBuilder.Build(nil))
		if err != nil {
			return nil, err
		}
		result.OutputFiles = append(result.OutputFiles, path)
	} else {
		for modelName, builder := range c.ModelClasses {
			path := c.Options.OutputPath + string(os.PathSeparator) + modelName + ".cs"
			err := c.WriteCodeFile(path, builder.Build(nil))
			if err != nil {
				return nil, err
			}
			result.OutputFiles = append(result.OutputFiles, path)
		}
	}

	return result, nil
}

func (c *CSharpGenerationContext) generateCodeForModel(model *CCLModel) error {
	var builder *codeBuilder.CodeBuilder
	if c.IsSingleFile {
		builder = c.SingleFileBuilder
	} else {
		builder = codeBuilder.NewCodeBuilderWithOptions(&codeBuilder.CodeBuilderOptions{
			IndentationStr:  "    ",
			NewLineStr:      "\n",
			EnableDebugInfo: c.Options.GenerateDebugInfo,
		})
		c.ModelClasses[model.Name] = builder
		builder.BeginSection(codeBuilder.SectionCommentHeaders)

		builder.AddCommentHeader("// THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.").
			DoImport("System", "using System;").
			DoImport("System.Collections.Generic", "using System.Collections.Generic;").
			DoImport("System.IO", "using System.IO;").
			DoImport("System.Text", "using System.Text;").
			AddNamespaceDeclaration("namespace " + c.CSharpNamespace).
			AppendNamespaceDeclaration("{")

		builder.EndSection()
	}

	builder.BeginSection(model.GetFullName())
	defer builder.EndSection()

	if !c.IsSingleFile {
		builder.Indent()
	}

	err := c.generateModelClass(builder, model)
	if err != nil {
		return err
	}

	if !c.IsSingleFile {
		builder.Unindent()
		builder.WriteLine("}")
	}

	return nil
}

func (c *CSharpGenerationContext) generateModelClass(builder *codeBuilder.CodeBuilder, model *CCLModel) error {
	builder.WriteLine("public class " + model.Name)
	builder.WriteLine("{")
	builder.Indent()

	// Write model ID constant
	modelIdConstName := "ModelId" + cclUtils.ToPascalCase(model.Name)
	builder.WriteLine("public const int " + modelIdConstName + " = " + ssg.ToBase10(model.ModelId) + ";")
	builder.NewLine()

	// Fields
	for _, field := range model.Fields {
		csType := c.getCSharpType(field)
		fieldName := c.toPascalCase(field.Name)
		// C# properties
		builder.WriteLine("public " + csType + " " + fieldName + " { get; set; }")
	}
	builder.NewLine()

	// Constructor
	builder.WriteLine("public " + model.Name + "()")
	builder.WriteLine("{")
	builder.Indent()
	for _, field := range model.Fields {
		fieldName := c.toPascalCase(field.Name)
		if field.IsArray() {
			csType := c.getCSharpType(field)
			// Initialize list
			builder.WriteLine(fieldName + " = new " + csType + "();")
		} else if field.Type.GetName() == cclValues.TypeNameBytes {
			builder.WriteLine(fieldName + " = new byte[0];")
		} else if field.Type.GetName() == cclValues.TypeNameString {
			builder.WriteLine(fieldName + " = \"\";")
		}
		// Primitives are auto-initialized to default values in C#, so we don't strictly need to do it,
		// but for consistency with other generators we can.
		// However, C# best practice is often to rely on default unless specific value needed.
		// String is null by default, so we initialized it to empty string above.
	}
	builder.Unindent()
	builder.WriteLine("}")
	builder.NewLine()

	// Get Model ID
	builder.WriteLine("public int GetModelId()")
	builder.WriteLine("{")
	builder.Indent()
	builder.WriteLine("return " + modelIdConstName + ";")
	builder.Unindent()
	builder.WriteLine("}")
	builder.NewLine()

	// Clone Empty
	builder.WriteLine("public " + model.Name + " CloneEmpty()")
	builder.WriteLine("{")
	builder.Indent()
	builder.WriteLine("return new " + model.Name + "();")
	builder.Unindent()
	builder.WriteLine("}")
	builder.NewLine()

	// Binary Serialization
	if c.NeedsBinarySerialization(CurrentLanguage, model) {
		if err := c.generateSerializeBinaryMethod(model, builder); err != nil {
			return err
		}
		if err := c.generateDeserializeBinaryMethod(model, builder); err != nil {
			return err
		}
	}

	builder.Unindent()
	builder.WriteLine("}")

	return nil
}
