package csGenerator

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/ALiwoto/ssg/ssg"
	"github.com/ALiwoto/ssg/ssg/caseUtils"
	gen "github.com/ccl-lang/ccl/src/cclGenerators"
	gValues "github.com/ccl-lang/ccl/src/core/globalValues"
	"github.com/ccl-lang/ccl/src/inputLangs/cclInput/cclErrors"
	"github.com/ccl-lang/ccl/src/inputLangs/cclInput/cclUtils/codeBuilder"
	"github.com/ccl-lang/ccl/src/inputLangs/cclInput/cclValues"
)

func (c *CSharpGenerationContext) generateCode() (*gen.CodeGenerationResult, error) {
	c.IsSingleFile, c.SingleFileName = c.IsSingleFileMode(CurrentLanguage)
	c.CSharpNamespace = c.getNamespace()

	if c.IsSingleFile {
		if c.SingleFileName == "" {
			c.SingleFileName = DefaultSingleFileName
		}

		c.SingleFileBuilder = codeBuilder.NewCodeBuilderWithOptions(&codeBuilder.CodeBuilderOptions{
			IndentationStr:  "    ",
			NewLineStr:      "\n",
			EnableDebugInfo: c.Options.GenerateDebugInfo,
		})
		c.SingleFileBuilder.BeginSection(codeBuilder.SectionCommentHeaders)
		c.SingleFileBuilder.AddCommentHeader("// THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.")
		c.SingleFileBuilder.EndSection()

		c.SingleFileBuilder.MapVarPairs(
			"namespace", c.CSharpNamespace,
		)
		c.SingleFileBuilder.WriteLine("using System;").
			WriteLine("using System.Collections.Generic;").
			WriteLine("using System.IO;").
			WriteLine("using System.Text;").
			WriteLine("using System.Text.Json.Nodes;").
			NewLine().
			LineD("namespace $namespace").
			WriteLine("{").
			Indent()
		c.SingleFileBuilder.UnmapVar("namespace")
	}

	// Generate each model class
	for _, typeDef := range c.GetGenerationTypeDefinitions() {
		if typeDef.IsCustomModel() {
			err := c.generateCodeForModel(typeDef.GetModelDefinition())
			if err != nil {
				return nil, err
			}
		} else if typeDef.IsCustomEnum() {
			enumDef := typeDef.GetEnumDefinition()
			if enumDef.IsNested() {
				continue
			}
			if err := c.generateCodeForEnum(enumDef); err != nil {
				return nil, err
			}
		} else {
			return nil, &cclErrors.UnsupportedTypeDefinitionError{
				TypeName:       typeDef.GetFullName(),
				TargetLanguage: CurrentLanguage.String(),
			}
		}
	}

	if c.IsSingleFile {
		c.SingleFileBuilder.Unindent()
		c.SingleFileBuilder.WriteLine("}")
	}

	result := &gen.CodeGenerationResult{
		SourceLanguage: gValues.LanguageCCL.String(),
		TargetLanguage: CurrentLanguage.String(),
		OutputFiles:    []string{},
	}

	if c.IsSingleFile {
		path := c.Options.OutputPath + string(os.PathSeparator) + c.SingleFileName
		err := c.WriteCodeFile(path, c.SingleFileBuilder.Build(nil))
		if err != nil {
			return nil, err
		}
		result.OutputFiles = append(result.OutputFiles, path)
	} else {
		for modelName, builder := range c.ModelClasses {
			path := c.Options.OutputPath + string(os.PathSeparator) + modelName + ".cs"
			err := c.WriteCodeFile(path, builder.Build(nil))
			if err != nil {
				return nil, err
			}
			result.OutputFiles = append(result.OutputFiles, path)
		}
	}

	return result, nil
}

func (c *CSharpGenerationContext) generateCodeForEnum(enumDef *CCLEnum) error {
	if c.IsSingleFile {
		return c.generateEnumDeclaration(c.SingleFileBuilder, enumDef)
	}

	builder := codeBuilder.NewCodeBuilderWithOptions(&codeBuilder.CodeBuilderOptions{
		IndentationStr:  "    ",
		NewLineStr:      "\n",
		EnableDebugInfo: c.Options.GenerateDebugInfo,
	})
	c.ModelClasses[enumDef.Name] = builder
	builder.BeginSection(codeBuilder.SectionCommentHeaders)
	builder.AddCommentHeader("// THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.").
		AddNamespaceDeclaration("namespace " + c.CSharpNamespace).
		AppendNamespaceDeclaration("{")
	builder.EndSection()

	builder.BeginSection(enumDef.GetFullName())
	defer builder.EndSection()
	builder.Indent()
	if err := c.generateEnumDeclaration(builder, enumDef); err != nil {
		return err
	}
	builder.Unindent()
	builder.WriteLine("}")
	return nil
}

func (c *CSharpGenerationContext) generateCodeForModel(model *CCLModel) error {
	var builder *codeBuilder.CodeBuilder
	if c.IsSingleFile {
		builder = c.SingleFileBuilder
	} else {
		builder = codeBuilder.NewCodeBuilderWithOptions(&codeBuilder.CodeBuilderOptions{
			IndentationStr:  "    ",
			NewLineStr:      "\n",
			EnableDebugInfo: c.Options.GenerateDebugInfo,
		})
		c.ModelClasses[model.Name] = builder
		builder.BeginSection(codeBuilder.SectionCommentHeaders)

		builder.AddCommentHeader("// THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.").
			DoImport("System", "using System;").
			DoImport("System.Collections.Generic", "using System.Collections.Generic;").
			DoImport("System.IO", "using System.IO;").
			DoImport("System.Text", "using System.Text;").
			DoImport("System.Text.Json.Nodes", "using System.Text.Json.Nodes;").
			AddNamespaceDeclaration("namespace " + c.CSharpNamespace).
			AppendNamespaceDeclaration("{")

		builder.EndSection()
	}

	builder.BeginSection(model.GetFullName())
	defer builder.EndSection()

	if !c.IsSingleFile {
		builder.Indent()
	}

	err := c.generateModelClass(builder, model)
	if err != nil {
		return err
	}

	if !c.IsSingleFile {
		builder.Unindent()
		builder.WriteLine("}")
	}

	return nil
}

func (c *CSharpGenerationContext) generateModelClass(builder *codeBuilder.CodeBuilder, model *CCLModel) error {
	modelIdConstName := "ModelId" + caseUtils.ToPascalCase(model.Name)
	builder.MapVarPairs(
		"model", model.Name,
		"modelIdConst", modelIdConstName,
		"modelId", ssg.ToBase10(model.ModelId),
	)
	defer builder.UnmapVar(
		"model",
		"modelIdConst",
		"modelId",
	)

	builder.LineD("public class $model").
		WriteLine("{").
		Indent()

	for _, enumDef := range model.Enums {
		if err := c.generateEnumDeclaration(builder, enumDef); err != nil {
			return err
		}
		builder.NewLine()
	}

	// Write model ID constant
	builder.LineD("public const int $modelIdConst = $modelId;").
		NewLine()

	// Fields
	for _, field := range model.Fields {
		csType := c.getCSharpType(field)
		fieldName := caseUtils.ToPascalCase(field.Name)
		builder.MapVarPairs(
			"field", fieldName,
			"type", csType,
		)
		// C# properties
		builder.LineD("public $type $field { get; set; }")
		builder.UnmapVar(
			"field",
			"type",
		)
	}
	builder.NewLine()

	// Constructor
	builder.LineD("public $model()").
		WriteLine("{").
		Indent()
	for _, field := range model.Fields {
		fieldName := caseUtils.ToPascalCase(field.Name)
		builder.MapVarPairs(
			"field", fieldName,
		)
		if field.IsArray() {
			csType := c.getCSharpType(field)
			builder.MapVarPairs(
				"type", csType,
			)
			// Initialize list
			builder.LineD("$field = new $type();")
			builder.UnmapVar("type")
		} else if field.Type.GetName() == cclValues.TypeNameBytes {
			builder.LineD("$field = new byte[0];")
		} else if field.Type.GetName() == cclValues.TypeNameString {
			builder.LineD(`$field = "";`)
		} else if field.HasDefaultValue() {
			defaultValue := csharpDefaultLiteral(field.GetDefaultValue())
			if enumRef := c.GetEnumDefaultReference(field); enumRef != nil {
				ref, err := c.getCSharpEnumReference(enumRef.Enum, enumRef.Member)
				if err != nil {
					return err
				}
				defaultValue = ref
			}
			builder.LineD("$field = " + defaultValue + ";")
		}
		builder.UnmapVar("field")
		// Primitives are auto-initialized to default values in C#, so we don't strictly need to do it,
		// but for consistency with other generators we can.
		// However, C# best practice is often to rely on default unless specific value needed.
		// String is null by default, so we initialized it to empty string above.
	}
	builder.Unindent().
		WriteLine("}").
		NewLine()

	// Get Model ID
	builder.WriteLine("public int GetModelId()").
		WriteLine("{").
		Indent().
		LineD("return $modelIdConst;").
		Unindent().
		WriteLine("}").
		NewLine()

	// Clone Empty
	builder.LineD("public $model CloneEmpty()").
		WriteLine("{").
		Indent().
		LineD("return new $model();").
		Unindent().
		WriteLine("}").
		NewLine()

	// Binary Serialization
	if c.NeedsBinarySerialization(CurrentLanguage, model) {
		if err := c.generateSerializeBinaryMethod(model, builder); err != nil {
			return err
		}
		if err := c.generateDeserializeBinaryMethod(model, builder); err != nil {
			return err
		}
	}
	if c.NeedsJsonSerialization(CurrentLanguage, model) {
		if err := c.generateSerializeJsonMethods(model, builder); err != nil {
			return err
		}
	}

	builder.Unindent().
		WriteLine("}")

	return nil
}

func (c *CSharpGenerationContext) generateEnumDeclaration(
	builder *codeBuilder.CodeBuilder,
	enumDef *CCLEnum,
) error {
	builder.WriteLine("public enum " + c.getCSharpEnumTypeName(enumDef) +
		" : " + c.getCSharpEnumBaseType(enumDef)).
		WriteLine("{").
		Indent()
	for _, member := range enumDef.Members {
		memberName, err := c.getCSharpEnumMemberName(enumDef, member)
		if err != nil {
			return err
		}
		builder.WriteLine(memberName + " = " + ssg.ToBase10(member.Value) + ",")
	}
	builder.Unindent().
		WriteLine("}")
	return nil
}

func (c *CSharpGenerationContext) getNamespace() string {
	// 1. Check for attribute on the first model (assuming all models in the same file share namespace preference if defined there)
	// Or we can check global attributes if CCL supports them.
	// The user said: "try to get #[CSharpNamespace("MyNamespace")] attribute"
	// We should check if any model has this attribute or if it's a file-level attribute (if supported).
	// Since we are generating for a set of models, let's check the first one or look for a common one.
	// Actually, the user might have meant an attribute on the model definition.
	// Let's check the first model's attributes.

	typeDefinitions := c.GetGenerationTypeDefinitions()
	if len(typeDefinitions) > 0 {
		firstModel := typeDefinitions[0]
		if firstModel.IsCustomModel() {
			model := firstModel.GetModelDefinition()
			attr := c.GetGlobalOrModelAttributes(gValues.LanguageCS, AttributeNamespace, model)
			if !attr.IsEmpty() {
				params := attr.GetParamsAtAsStrings(0)
				if len(params) > 0 {
					return params[0]
				}
			}
		}
	}

	// 2. Peek at parent directory
	parentDir := filepath.Dir(c.Options.OutputPath)
	baseNamespace := ""
	foundCsFile := false

	entries, err := os.ReadDir(parentDir)
	if err == nil {
		for _, entry := range entries {
			if !entry.IsDir() && strings.HasSuffix(entry.Name(), ".cs") {
				content, err := os.ReadFile(filepath.Join(parentDir, entry.Name()))
				if err == nil {
					matches := csNamespaceRegex.FindStringSubmatch(string(content))
					if len(matches) > 1 {
						baseNamespace = matches[1]
						foundCsFile = true
						break
					}
				}
			}
		}
	}

	if foundCsFile {
		targetDirName := filepath.Base(c.Options.OutputPath)
		return baseNamespace + "." + targetDirName
	}

	// 3. Default
	return DefaultNamespace
}

func (c *CSharpGenerationContext) getCSharpType(field *CCLField) string {
	targetType := field.Type
	if targetType.IsArray() {
		targetType = targetType.GetUnderlyingType()
	}

	csType := c.getCSharpBuiltinTypeName(targetType.GetName())
	if csType == "" {
		if targetType.IsCustomTypeEnum() {
			csType = c.getCSharpEnumTypeName(targetType.GetDefinition().GetEnumDefinition())
		} else if targetType.IsCustomTypeModel() {
			csType = targetType.GetName()
		} else {
			csType = "object"
		}
	}

	if field.IsArray() {
		if targetType.IsCustomTypeModel() {
			csType = "List<" + csType + ">"
		} else {
			csType = "List<" + csType + ">"
		}
	}

	return csType
}
