package pyGenerator

import (
	"os"

	"github.com/ALiwoto/ssg/ssg"
	"github.com/ccl-lang/ccl/src/core/cclUtils/codeBuilder"
)

func (c *PythonGenerationContext) generateInitFile() error {
	builder := codeBuilder.NewCodeBuilder()
	builder.BeginSection("init")
	defer builder.EndSection()

	builder.AddCommentHeader("# THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.").
		WriteLine("__all__ = [").
		Indent()

	// Import all classes
	for _, typeDef := range c.Options.CCLDefinition.TypeDefinitions {
		if !typeDef.IsCustomModel() {
			continue
		}

		importLine, err := c.getImportLineForType(typeDef)
		if err != nil {
			return err
		}
		builder.DoImport(typeDef.GetFullName(), importLine)

		builder.WriteLine("\"" + typeDef.GetName() + "\",")
	}

	builder.Unindent()
	builder.WriteLine("]")

	path := c.Options.OutputPath + string(os.PathSeparator) + "__init__.py"
	return ssg.WriteFileStr(path, builder.String(nil))
}
