package pyGenerator

import (
	"os"

	"github.com/ALiwoto/ssg/ssg"
	"github.com/ccl-lang/ccl/src/core/cclUtils/codeBuilder"
)

func (c *PythonGenerationContext) generateInitFile() error {
	builder := codeBuilder.NewCodeBuilder()
	builder.WriteLine("# THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.").
		NewLine()

	// Import all classes
	for modelName := range c.ModelClasses {
		moduleName := toSnakeCase(modelName)
		builder.WriteLine("from ." + moduleName + " import " + modelName)
	}
	builder.NewLine()

	// Add to __all__
	builder.WriteLine("__all__ = [")
	builder.Indent()
	for modelName := range c.ModelClasses {
		builder.WriteLine("\"" + modelName + "\",")
	}
	builder.Unindent()
	builder.WriteLine("]")

	path := c.Options.OutputPath + string(os.PathSeparator) + "__init__.py"
	return ssg.WriteFileStr(path, builder.String())
}
