package pyGenerator

import (
	"os"
	"strings"

	"github.com/ALiwoto/ssg/ssg"
	"github.com/ccl-lang/ccl/src/core/cclErrors"
	"github.com/ccl-lang/ccl/src/core/cclUtils/codeBuilder"
	"github.com/ccl-lang/ccl/src/core/cclValues"
	gValues "github.com/ccl-lang/ccl/src/core/globalValues"
)

func (c *PythonGenerationContext) GenerateCode() error {
	c.ModelClasses = make(map[string]*codeBuilder.CodeBuilder)

	// Generate each model class
	for i := range c.Options.CCLDefinition.TypeDefinitions {
		typeDef := c.Options.CCLDefinition.TypeDefinitions[i]
		if typeDef.IsCustomModel() {
			err := c.generateCodeForModel(typeDef.GetModelDefinition())
			if err != nil {
				return err
			}
		} else {
			// for now, we only support model types
			return &cclErrors.UnsupportedTypeDefinitionError{
				TypeName:       typeDef.GetFullName(),
				TargetLanguage: CurrentLanguage.String(),
			}
		}
	}

	// Generate __init__.py
	if err := c.generateInitFile(); err != nil {
		return err
	}

	return nil
}

func (c *PythonGenerationContext) generateCodeForModel(model *CCLModel) error {
	modelName := model.GetFullName()
	builder := codeBuilder.NewCodeBuilder()
	c.ModelClasses[modelName] = builder

	builder.BeginSection(modelName)
	defer builder.EndSection()

	err := c.generateModelClass(builder, model)
	if err != nil {
		return err
	}

	// Generate methods
	if c.NeedsBinarySerialization(gValues.LanguagePy, model) {
		if err = c.generateSerializeBinaryMethod(model, builder); err != nil {
			return err
		}

		if err = c.generateDeserializeBinaryMethod(model, builder); err != nil {
			return err
		}
	}

	path := c.Options.OutputPath + string(os.PathSeparator)
	fileName, err := c.GetFileNameForModel(
		gValues.LanguagePy,
		model,
		DefaultFileNamingStyle,
		supportedStyles,
	)
	if err != nil {
		return err
	}

	err = ssg.WriteFileStr(path+fileName+".py", builder.String(nil))
	if err != nil {
		return err
	}

	// We keep the builder in the map for __init__.py generation
	return nil
}

func (c *PythonGenerationContext) generateModelClass(builder *codeBuilder.CodeBuilder, model *CCLModel) error {
	// Write class header
	builder.AddCommentHeader("# THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.").
		DoImport("annotations", "from __future__ import annotations").
		DoImport("struct", "import struct")

	builder.WriteLine("class " + model.Name + ":").
		Indent()

	// Write model ID constant
	modelIdConstName := "MODEL_ID_" + strings.ToUpper(toSnakeCase(model.Name))
	builder.WriteLine(modelIdConstName + " = " + ssg.ToBase10(model.ModelId)).
		NewLine()

	// Write __init__ method
	builder.WriteLine("def __init__(self):").
		Indent()

	if len(model.Fields) == 0 {
		builder.WriteLine("pass")
	} else {
		for _, field := range model.Fields {
			varType := c.getPythonType(field)
			defaultValue := "None"
			if field.IsArray() {
				defaultValue = "[]"
			} else {
				switch field.Type.GetName() {
				case cclValues.TypeNameInt, cclValues.TypeNameInt8, cclValues.TypeNameInt16, cclValues.TypeNameInt32, cclValues.TypeNameInt64,
					cclValues.TypeNameUint, cclValues.TypeNameUint8, cclValues.TypeNameUint16, cclValues.TypeNameUint32, cclValues.TypeNameUint64:
					defaultValue = "0"
				case cclValues.TypeNameFloat, cclValues.TypeNameFloat32, cclValues.TypeNameFloat64:
					defaultValue = "0.0"
				case cclValues.TypeNameBool:
					defaultValue = "False"
				case cclValues.TypeNameString:
					defaultValue = "\"\""
				case cclValues.TypeNameBytes:
					defaultValue = "b\"\""
				}
			}

			if field.IsCustomTypeModel() {
				// this needs extra import
				importLine, err := c.getImportLineForType(field.Type.GetDefinition())
				if err != nil {
					return err
				}
				builder.DoImport(field.GetFullTypeName(), importLine)
			}
			fieldName := toSnakeCase(field.Name)
			builder.WriteLine("self." + fieldName + ": " + varType + " = " + defaultValue)
		}
	}
	builder.UnindentLine().
		NewLine()

	// Add get_model_id method
	builder.WriteLine("def get_model_id(self) -> int:").
		Indent().
		WriteLine("return " + model.Name + "." + modelIdConstName).
		UnindentLine().
		NewLine()

	// Add clone_empty method
	builder.WriteLine("def clone_empty(self) -> \"" + model.Name + "\":").
		Indent().
		WriteLine("return " + model.Name + "()").
		UnindentLine().
		NewLine()

	return nil
}

// getImportLineForType returns the import line for a given type definition.
// TODO: this implementation lacks proper relative module path handling.
func (c *PythonGenerationContext) getImportLineForType(targetType *cclValues.CCLTypeDefinition) (string, error) {
	fileName, err := c.GetFileNameForModel(
		gValues.LanguagePy,
		targetType.GetModelDefinition(),
		DefaultFileNamingStyle,
		supportedStyles,
	)
	if err != nil {
		return "", err
	}

	// TODO: handle relative imports based on package structure and "current" file location
	return "from ." + fileName + " import " + targetType.GetShortModelName(), nil
}

func (c *PythonGenerationContext) getPythonType(field *cclValues.ModelFieldDefinition) string {
	targetType := field.Type
	if targetType.IsArray() {
		targetType = targetType.GetUnderlyingType()
	}

	pyType := ""
	switch targetType.GetName() {
	case cclValues.TypeNameString:
		pyType = "str"
	case cclValues.TypeNameInt, cclValues.TypeNameInt8, cclValues.TypeNameInt16, cclValues.TypeNameInt32, cclValues.TypeNameInt64,
		cclValues.TypeNameUint, cclValues.TypeNameUint8, cclValues.TypeNameUint16, cclValues.TypeNameUint32, cclValues.TypeNameUint64:
		pyType = "int"
	case cclValues.TypeNameFloat, cclValues.TypeNameFloat32, cclValues.TypeNameFloat64:
		pyType = "float"
	case cclValues.TypeNameBool:
		pyType = "bool"
	case cclValues.TypeNameBytes:
		pyType = "bytes"
	case cclValues.TypeNameDateTime:
		pyType = "int" // Using int64 timestamp
	default:
		if targetType.IsCustomTypeModel() {
			pyType = targetType.GetName()
		} else {
			// Fallback or error?
			pyType = "Any" // Should probably import Any from typing
		}
	}

	if field.IsArray() {
		pyType = "list[" + pyType + "]"
	}

	return pyType
}
