package pyGenerator

import (
	"os"
	"strings"

	"github.com/ALiwoto/ssg/ssg"
	"github.com/ALiwoto/ssg/ssg/caseUtils"
	gValues "github.com/ccl-lang/ccl/src/core/globalValues"
	"github.com/ccl-lang/ccl/src/inputLangs/cclInput/cclErrors"
	"github.com/ccl-lang/ccl/src/inputLangs/cclInput/cclUtils/codeBuilder"
	"github.com/ccl-lang/ccl/src/inputLangs/cclInput/cclValues"
)

func (c *PythonGenerationContext) GenerateCode() error {
	c.ModelClasses = make(map[string]*codeBuilder.CodeBuilder)
	c.OutputFiles = []string{}

	// Generate each model class
	for _, typeDef := range c.GetGenerationTypeDefinitions() {
		if typeDef.IsCustomModel() {
			err := c.generateCodeForModel(typeDef.GetModelDefinition())
			if err != nil {
				return err
			}
		} else if typeDef.IsCustomEnum() {
			enumDef := typeDef.GetEnumDefinition()
			if enumDef.IsNested() {
				continue
			}
			if err := c.generateCodeForEnum(enumDef); err != nil {
				return err
			}
		} else {
			return &cclErrors.UnsupportedTypeDefinitionError{
				TypeName:       typeDef.GetFullName(),
				TargetLanguage: CurrentLanguage.String(),
			}
		}
	}

	// Generate __init__.py
	if err := c.generateInitFile(); err != nil {
		return err
	}
	c.OutputFiles = append(c.OutputFiles, c.Options.OutputPath+string(os.PathSeparator)+"__init__.py")

	return nil
}

func (c *PythonGenerationContext) generateCodeForEnum(enumDef *CCLEnum) error {
	builder := codeBuilder.NewCodeBuilderWithOptions(&codeBuilder.CodeBuilderOptions{
		IndentationStr:  "\t",
		NewLineStr:      "\n",
		EnableDebugInfo: c.Options.GenerateDebugInfo,
	})

	builder.BeginSection(enumDef.GetFullName())
	defer builder.EndSection()
	builder.AddCommentHeader("# THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.").
		DoImport("enum", "from enum import IntEnum")
	if err := c.generateEnumClass(builder, enumDef); err != nil {
		return err
	}

	fullPath := c.Options.OutputPath + string(os.PathSeparator) + pythonEnumFileName(enumDef) + ".py"
	if err := c.WriteCodeFile(fullPath, builder.Build(nil)); err != nil {
		return err
	}
	c.OutputFiles = append(c.OutputFiles, fullPath)
	return nil
}

func (c *PythonGenerationContext) generateCodeForModel(model *CCLModel) error {
	modelName := model.GetFullName()
	builder := codeBuilder.NewCodeBuilderWithOptions(&codeBuilder.CodeBuilderOptions{
		IndentationStr:  "\t",
		NewLineStr:      "\n",
		EnableDebugInfo: c.Options.GenerateDebugInfo,
	})
	c.ModelClasses[modelName] = builder

	builder.BeginSection(modelName)
	defer builder.EndSection()

	err := c.generateModelClass(builder, model)
	if err != nil {
		return err
	}

	// Generate methods
	if c.NeedsBinarySerialization(gValues.LanguagePy, model) {
		if err = c.generateSerializeBinaryMethod(model, builder); err != nil {
			return err
		}

		if err = c.generateDeserializeBinaryMethod(model, builder); err != nil {
			return err
		}
	}
	if c.NeedsJsonSerialization(gValues.LanguagePy, model) {
		if err = c.generateSerializeJsonMethods(model, builder); err != nil {
			return err
		}
	}

	path := c.Options.OutputPath + string(os.PathSeparator)
	fileName, err := c.GetFileNameForModel(
		gValues.LanguagePy,
		model,
		DefaultFileNamingStyle,
		supportedFileNameStyles,
	)
	if err != nil {
		return err
	}

	fullPath := path + fileName + ".py"
	err = c.WriteCodeFile(fullPath, builder.Build(nil))
	if err != nil {
		return err
	}
	c.OutputFiles = append(c.OutputFiles, fullPath)

	// We keep the builder in the map for __init__.py generation
	return nil
}

func (c *PythonGenerationContext) generateModelClass(builder *codeBuilder.CodeBuilder, model *CCLModel) error {
	modelIdConstName := "MODEL_ID_" + strings.ToUpper(caseUtils.ToSnakeCase(model.Name))
	builder.MapVarPairs(
		"model", model.Name,
		"modelIdConst", modelIdConstName,
		"modelId", ssg.ToBase10(model.ModelId),
	)
	defer builder.UnmapVar(
		"model",
		"modelIdConst",
		"modelId",
	)

	// Write class header
	builder.AddCommentHeader("# THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.").
		DoImport("annotations", "from __future__ import annotations").
		DoImport("struct", "import struct")
	if len(model.Enums) > 0 {
		builder.DoImport("enum", "from enum import IntEnum")
	}

	builder.LineD("class $model:").
		Indent()

	for _, enumDef := range model.Enums {
		if err := c.generateEnumClass(builder, enumDef); err != nil {
			return err
		}
	}

	// Write model ID constant
	builder.LineD("$modelIdConst = $modelId").
		NewLine()

	// Write __init__ method
	builder.WriteLine("def __init__(self):").
		Indent()

	if len(model.Fields) == 0 {
		builder.WriteLine("pass")
	} else {
		for _, field := range model.Fields {
			varType, err := c.getPythonType(field)
			if err != nil {
				return err
			}
			defaultValue := "None"
			if field.IsArray() {
				defaultValue = "[]"
			} else if field.HasDefaultValue() {
				defaultValue = pythonDefaultLiteral(field.GetDefaultValue())
				if enumRef := c.GetEnumDefaultReference(field); enumRef != nil {
					ref, err := c.getPythonEnumReference(enumRef.Enum, enumRef.Member)
					if err != nil {
						return err
					}
					defaultValue = ref
				}
			} else {
				switch field.Type.GetName() {
				case cclValues.TypeNameInt, cclValues.TypeNameInt8, cclValues.TypeNameInt16, cclValues.TypeNameInt32, cclValues.TypeNameInt64,
					cclValues.TypeNameUint, cclValues.TypeNameUint8, cclValues.TypeNameUint16, cclValues.TypeNameUint32, cclValues.TypeNameUint64:
					defaultValue = "0"
				case cclValues.TypeNameFloat, cclValues.TypeNameFloat32, cclValues.TypeNameFloat64:
					defaultValue = "0.0"
				case cclValues.TypeNameBool:
					defaultValue = "False"
				case cclValues.TypeNameString:
					defaultValue = "\"\""
				case cclValues.TypeNameBytes:
					defaultValue = "b\"\""
				}
			}

			importType := field.Type
			if field.IsArray() {
				importType = importType.GetUnderlyingType()
			}

			if importType != nil && importType.IsCustomTypeModel() {
				// this needs extra import
				importLine, err := c.getImportLineForType(importType.GetDefinition())
				if err != nil {
					return err
				}
				builder.DoImport(importType.GetDefinition().GetFullName(), importLine)
			} else if importType != nil && importType.IsCustomTypeEnum() {
				enumDef := importType.GetDefinition().GetEnumDefinition()
				if !enumDef.IsNested() || enumDef.OwnedBy != model {
					importLine, err := c.getImportLineForEnum(enumDef)
					if err != nil {
						return err
					}
					builder.DoImport(enumDef.GetFullName(), importLine)
				}
			}
			fieldName := caseUtils.ToSnakeCase(field.Name)
			builder.MapVarPairs(
				"defaultValue", defaultValue,
				"field", fieldName,
				"type", varType,
			)
			builder.LineD("self.$field: $type = $defaultValue")
			builder.UnmapVar(
				"defaultValue",
				"field",
				"type",
			)
		}
	}
	builder.UnindentLine().
		NewLine()

	// Add get_model_id method
	builder.WriteLine("def get_model_id(self) -> int:").
		Indent().
		LineD("return $model.$modelIdConst").
		UnindentLine().
		NewLine()

	// Add clone_empty method
	builder.LineD(`def clone_empty(self) -> "$model":`).
		Indent().
		LineD("return $model()").
		UnindentLine().
		NewLine()

	if err := c.generateDeepCloneMethod(model, builder); err != nil {
		return err
	}

	return nil
}

// getImportLineForType returns the import line for a given type definition.
// TODO: this implementation lacks proper relative module path handling.
func (c *PythonGenerationContext) getImportLineForType(targetType *cclValues.CCLTypeDefinition) (string, error) {
	fileName, err := c.GetFileNameForModel(
		gValues.LanguagePy,
		targetType.GetModelDefinition(),
		DefaultFileNamingStyle,
		supportedFileNameStyles,
	)
	if err != nil {
		return "", err
	}

	// TODO: handle relative imports based on package structure and "current" file location
	return "from ." + fileName + " import " + targetType.GetShortModelName(), nil
}

func (c *PythonGenerationContext) getPythonType(field *cclValues.ModelFieldDefinition) (string, error) {
	targetType := field.Type
	if targetType.IsArray() {
		targetType = targetType.GetUnderlyingType()
	}

	pyType := ""
	switch targetType.GetName() {
	case cclValues.TypeNameString:
		pyType = "str"
	case cclValues.TypeNameInt, cclValues.TypeNameInt8, cclValues.TypeNameInt16, cclValues.TypeNameInt32, cclValues.TypeNameInt64,
		cclValues.TypeNameUint, cclValues.TypeNameUint8, cclValues.TypeNameUint16, cclValues.TypeNameUint32, cclValues.TypeNameUint64:
		pyType = "int"
	case cclValues.TypeNameFloat, cclValues.TypeNameFloat32, cclValues.TypeNameFloat64:
		pyType = "float"
	case cclValues.TypeNameBool:
		pyType = "bool"
	case cclValues.TypeNameBytes:
		pyType = "bytes"
	case cclValues.TypeNameDateTime:
		pyType = "int" // Using int64 timestamp
	default:
		if targetType.IsCustomTypeEnum() {
			enumTypeName, err := c.getPythonEnumTypeName(targetType.GetDefinition().GetEnumDefinition())
			if err != nil {
				return "", err
			}
			pyType = enumTypeName
		} else if targetType.IsCustomTypeModel() {
			pyType = targetType.GetName()
		} else {
			// Fallback or error?
			pyType = "Any" // Should probably import Any from typing
		}
	}

	if field.IsArray() {
		pyType = "list[" + pyType + "]"
	}

	return pyType, nil
}
