package pyGenerator

import (
	"errors"
	"os"
	"strings"

	"github.com/ALiwoto/ssg/ssg"
	"github.com/ccl-lang/ccl/src/core/cclErrors"
	"github.com/ccl-lang/ccl/src/core/cclUtils/codeBuilder"
	"github.com/ccl-lang/ccl/src/core/cclValues"
	"github.com/ccl-lang/ccl/src/core/globalValues"
)

func (c *PythonGenerationContext) GenerateCode() error {
	c.ModelClasses = make(map[string]*codeBuilder.CodeBuilder)

	// Generate each model class
	for i := range c.Options.CCLDefinition.TypeDefinitions {
		typeDef := c.Options.CCLDefinition.TypeDefinitions[i]
		if typeDef.IsCustomModel() {
			err := c.generateCodeForMode(typeDef.GetModelDefinition())
			if err != nil {
				return err
			}
		} else {
			// for now, we only support model types
			return &cclErrors.UnsupportedTypeDefinitionError{
				TypeName:       typeDef.GetFullName(),
				TargetLanguage: LanguageName,
			}
		}
	}

	// Generate __init__.py
	if err := c.generateInitFile(); err != nil {
		return err
	}

	return nil
}

func (c *PythonGenerationContext) generateCodeForMode(model *CCLModel) error {
	err := c.GenerateModelClass(model)
	if err != nil {
		return err
	}

	// Get the builder for this model
	builder := c.ModelClasses[model.Name]
	if builder == nil {
		return errors.New("GenerateCode: Unexpected error: model class builder not found after generation")
	}

	// Generate methods
	if c.NeedsBinarySerialization(globalValues.LanguagePy, model) {
		if err = c.generateSerializeBinaryMethod(model, builder); err != nil {
			return err
		}

		if err = c.generateDeserializeBinaryMethod(model, builder); err != nil {
			return err
		}
	}

	path := c.Options.OutputPath + string(os.PathSeparator)
	fileName := toSnakeCase(model.Name) + ".py"
	err = ssg.WriteFileStr(path+fileName, builder.String())
	if err != nil {
		return err
	}

	// We keep the builder in the map for __init__.py generation
	return nil
}

func (c *PythonGenerationContext) GenerateModelClass(model *CCLModel) error {
	builder := codeBuilder.NewCodeBuilder()
	c.ModelClasses[model.Name] = builder

	// Write class header
	builder.WriteLine("# THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.").
		NewLine().
		WriteLine("from __future__ import annotations").
		NewLine().
		WriteLine("import struct").
		NewLine()

	builder.WriteLine("class " + model.Name + ":").
		Indent()

	// Write model ID constant
	modelIdConstName := "MODEL_ID_" + strings.ToUpper(toSnakeCase(model.Name))
	builder.WriteLine(modelIdConstName + " = " + ssg.ToBase10(model.ModelId)).
		NewLine()

	// Write __init__ method
	builder.WriteLine("def __init__(self):").
		Indent()

	if len(model.Fields) == 0 {
		builder.WriteLine("pass")
	} else {
		for _, field := range model.Fields {
			varType := c.getPythonType(field)
			defaultValue := "None"
			if field.IsArray() {
				defaultValue = "[]"
			} else {
				switch field.Type.GetName() {
				case cclValues.TypeNameInt, cclValues.TypeNameInt8, cclValues.TypeNameInt16, cclValues.TypeNameInt32, cclValues.TypeNameInt64,
					cclValues.TypeNameUint, cclValues.TypeNameUint8, cclValues.TypeNameUint16, cclValues.TypeNameUint32, cclValues.TypeNameUint64:
					defaultValue = "0"
				case cclValues.TypeNameFloat, cclValues.TypeNameFloat32, cclValues.TypeNameFloat64:
					defaultValue = "0.0"
				case cclValues.TypeNameBool:
					defaultValue = "False"
				case cclValues.TypeNameString:
					defaultValue = "\"\""
				case cclValues.TypeNameBytes:
					defaultValue = "b\"\""
				}
			}

			fieldName := toSnakeCase(field.Name)
			builder.WriteLine("self." + fieldName + ": " + varType + " = " + defaultValue)
		}
	}
	builder.UnindentLine().
		NewLine()

	// Add get_model_id method
	builder.WriteLine("def get_model_id(self) -> int:").
		Indent().
		WriteLine("return " + model.Name + "." + modelIdConstName).
		UnindentLine().
		NewLine()

	// Add clone_empty method
	builder.WriteLine("def clone_empty(self) -> " + model.Name + ":").
		Indent().
		WriteLine("return " + model.Name + "()").
		UnindentLine().
		NewLine()

	return nil
}

func (c *PythonGenerationContext) IsCustomType(cclType string) bool {
	return c.Options.CCLDefinition.IsCustomType(cclType)
}

func (c *PythonGenerationContext) getPythonType(field *cclValues.ModelFieldDefinition) string {
	targetType := field.Type
	if targetType.IsArray() {
		targetType = targetType.GetUnderlyingType()
	}

	pyType := ""
	switch targetType.GetName() {
	case cclValues.TypeNameString:
		pyType = "str"
	case cclValues.TypeNameInt, cclValues.TypeNameInt8, cclValues.TypeNameInt16, cclValues.TypeNameInt32, cclValues.TypeNameInt64,
		cclValues.TypeNameUint, cclValues.TypeNameUint8, cclValues.TypeNameUint16, cclValues.TypeNameUint32, cclValues.TypeNameUint64:
		pyType = "int"
	case cclValues.TypeNameFloat, cclValues.TypeNameFloat32, cclValues.TypeNameFloat64:
		pyType = "float"
	case cclValues.TypeNameBool:
		pyType = "bool"
	case cclValues.TypeNameBytes:
		pyType = "bytes"
	case cclValues.TypeNameDateTime:
		pyType = "int" // Using int64 timestamp
	default:
		if c.IsCustomType(targetType.GetName()) {
			pyType = targetType.GetName()
		} else {
			// Fallback or error?
			pyType = "Any" // Should probably import Any from typing
		}
	}

	if field.IsArray() {
		pyType = "list[" + pyType + "]"
	}

	return pyType
}
