package pyGenerator

import (
	"os"

	"github.com/ccl-lang/ccl/src/inputLangs/cclInput/cclUtils/codeBuilder"
)

func (c *PythonGenerationContext) generateInitFile() error {
	builder := codeBuilder.NewCodeBuilderWithOptions(&codeBuilder.CodeBuilderOptions{
		IndentationStr:  "\t",
		NewLineStr:      "\n",
		EnableDebugInfo: c.Options.GenerateDebugInfo,
	})
	builder.BeginSection("init")
	defer builder.EndSection()

	builder.AddCommentHeader("# THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.").
		WriteLine("__all__ = [").
		Indent()

	// Import all classes
	for _, typeDef := range c.GetGenerationTypeDefinitions() {
		if typeDef.IsCustomModel() {
			importLine, err := c.getImportLineForType(typeDef)
			if err != nil {
				return err
			}
			builder.DoImport(typeDef.GetFullName(), importLine)

			builder.WriteLine("\"" + typeDef.GetName() + "\",")
			continue
		}

		if typeDef.IsCustomEnum() {
			enumDef := typeDef.GetEnumDefinition()
			if enumDef.IsNested() {
				continue
			}

			importLine, err := c.getImportLineForEnum(enumDef)
			if err != nil {
				return err
			}
			builder.DoImport(enumDef.GetFullName(), importLine)

			enumTypeName, err := c.getPythonEnumLocalTypeName(enumDef)
			if err != nil {
				return err
			}
			builder.WriteLine("\"" + enumTypeName + "\",")
		}
	}

	builder.Unindent()
	builder.WriteLine("]")

	path := c.Options.OutputPath + string(os.PathSeparator) + "__init__.py"
	return c.WriteCodeFile(path, builder.Build(nil))
}
