// THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.

package apiTypes_gen

import (
	"time"
)

type AuthRequest struct {
	Username string
	Password string
}

type AuthResponse struct {
	Token string
	UserId int64
	ProfileImage []byte
}

type UserInfo struct {
	Id int64
	Username string
	Email string
	ProfileImage []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}

type GetUsersResult struct {
	Users []*UserInfo
	OtherUsers []*UserInfo
}

