program         = { import_declaration | namespace_declaration | scoped_attribute | model_definition } ;
import_declaration = 'import', string_literal, ';' ;
namespace_declaration = 'namespace', namespace_name, ';' ;
scoped_attribute = '#', [ attribute_scope, ':' ], '[', [ language_selector, ':' ], attribute_body, ']' ;
attribute_scope = 'file' | 'global' | 'namespace' ;
language_selector = '$', language_name, { ',', '$', language_name } ;
attribute_body  = identifier, [ '(', [ attribute_parameter, { ',', attribute_parameter } ], ')' ] ;
attribute_parameter = [ identifier, '=' ], attribute_value ;
attribute_value = string_literal | int_literal | float_literal | reserved_literal | identifier ;
model_definition = { local_attribute }, 'model', identifier, '{', { field_definition }, '}' ;
local_attribute  = '[', [ language_selector, ':' ], attribute_body, ']' ;
field_definition = identifier, ':', type_expression, ';' ;
type_expression  = identifier, [ '[', ']' ] ;
namespace_name   = identifier, { '.', identifier } ;
language_name    = identifier ;
string_literal   = STRING_LITERAL ;
int_literal      = INT_LITERAL ;
float_literal    = FLOAT_LITERAL ;
reserved_literal = RESERVED_LITERAL ;
identifier       = IDENTIFIER ;

// Terminal symbols (tokens):
'#'              = HASH ;
'['              = LEFT_BRACKET ;
']'              = RIGHT_BRACKET ;
'('              = LEFT_PARENTHESIS ;
')'              = RIGHT_PARENTHESIS ;
'$'              = DOLLAR ;
'import'        = KEYWORD_IMPORT ;
'namespace'     = KEYWORD_NAMESPACE ;
'model'          = KEYWORD_MODEL ;
':'              = COLON ;
';'              = SEMICOLON ;
','              = COMMA ;
'.'              = DOT ;
'='              = ASSIGNMENT ;
'{'              = LEFT_BRACE ;
'}'              = RIGHT_BRACE ;
STRING_LITERAL   = /* A sequence of characters enclosed in double quotes */ ;
INT_LITERAL      = /* An integer literal */ ;
FLOAT_LITERAL    = /* A floating-point literal */ ;
RESERVED_LITERAL = /* true, false, null, nil, self, super, this, etc. */ ;
IDENTIFIER       = /* Any alphanumeric sequence starting with a letter */ ;
