package jsGenerator

import (
	"os"
	"strings"

	"github.com/ALiwoto/ssg/ssg"
	gen "github.com/ccl-lang/ccl/src/cclGenerators"
	"github.com/ccl-lang/ccl/src/core/cclErrors"
	"github.com/ccl-lang/ccl/src/core/cclUtils"
	"github.com/ccl-lang/ccl/src/core/cclUtils/codeBuilder"
	"github.com/ccl-lang/ccl/src/core/cclValues"
	gValues "github.com/ccl-lang/ccl/src/core/globalValues"
)

func (c *JavaScriptGenerationContext) generateCode() (*gen.CodeGenerationResult, error) {
	c.IsSingleFile, c.SingleFileName = c.IsSingleFileMode(LanguageName)

	if c.IsSingleFile {
		if c.SingleFileName == "" {
			c.SingleFileName = "generated.js"
		}

		c.SingleFileBuilder = codeBuilder.NewCodeBuilderWithOptions(&codeBuilder.CodeBuilderOptions{
			IndentationStr:  "\t",
			NewLineStr:      "\n",
			EnableDebugInfo: c.Options.GenerateDebugInfo,
		})
		c.SingleFileBuilder.BeginSection(codeBuilder.SectionCommentHeaders)
		c.SingleFileBuilder.AddCommentHeader("// THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.")
		c.SingleFileBuilder.EndSection()
	}

	// Generate each model class
	for _, typeDef := range c.Options.CCLDefinition.TypeDefinitions {
		if typeDef.IsCustomModel() {
			err := c.generateCodeForModel(typeDef.GetModelDefinition())
			if err != nil {
				return nil, err
			}
		} else {
			// for now, we only support model types
			return nil, &cclErrors.UnsupportedTypeDefinitionError{
				TypeName:       typeDef.GetFullName(),
				TargetLanguage: LanguageName.String(),
			}
		}
	}

	result := &gen.CodeGenerationResult{
		SourceLanguage: gValues.LanguageCCL.String(),
		TargetLanguage: gValues.LanguageJS.String(),
		OutputFiles:    []string{},
	}

	if c.IsSingleFile {
		path := c.Options.OutputPath + string(os.PathSeparator) + c.SingleFileName
		err := c.WriteCodeFile(path, c.SingleFileBuilder.Build(nil))
		if err != nil {
			return nil, err
		}
		result.OutputFiles = append(result.OutputFiles, path)
	} else {
		for modelName, builder := range c.ModelClasses {
			path := c.Options.OutputPath + string(os.PathSeparator) + modelName + ".js"
			err := c.WriteCodeFile(path, builder.Build(nil))
			if err != nil {
				return nil, err
			}
			result.OutputFiles = append(result.OutputFiles, path)
		}
	}

	return result, nil
}

func (c *JavaScriptGenerationContext) generateCodeForModel(model *CCLModel) error {
	var builder *codeBuilder.CodeBuilder
	if c.IsSingleFile {
		builder = c.SingleFileBuilder
	} else {
		builder = codeBuilder.NewCodeBuilderWithOptions(&codeBuilder.CodeBuilderOptions{
			IndentationStr:  "\t",
			NewLineStr:      "\n",
			EnableDebugInfo: c.Options.GenerateDebugInfo,
		})
		c.ModelClasses[model.Name] = builder
	}

	builder.BeginSection(model.GetFullName())
	defer builder.EndSection()

	if !c.IsSingleFile {
		builder.AddCommentHeader("// THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.")
	}

	// In multi-file mode, we need to import other models if they are referenced.
	if !c.IsSingleFile {
		for _, field := range model.Fields {
			targetType := field.Type
			if targetType.IsArray() {
				targetType = targetType.GetUnderlyingType()
			}
			if targetType.IsCustomTypeModel() {
				// Import the custom type
				// Assuming same directory for now
				builder.DoImport(targetType.GetName(), "import { "+targetType.GetName()+" } from './"+targetType.GetName()+".js';")
			}
		}
	}

	err := c.generateModelClass(builder, model)
	if err != nil {
		return err
	}

	return nil
}

func (c *JavaScriptGenerationContext) generateModelClass(builder *codeBuilder.CodeBuilder, model *CCLModel) error {
	builder.WriteLine("export class " + model.Name + " {").
		Indent()

	// Write model ID constant
	modelIdConstName := "MODEL_ID_" + strings.ToUpper(cclUtils.ToSnakeCase(model.Name))
	builder.WriteLine("static " + modelIdConstName + " = " + ssg.ToBase10(model.ModelId) + ";").
		NewLine()

	// Fields
	for _, field := range model.Fields {
		fieldName := cclUtils.ToCamelCase(field.Name)
		builder.WriteLine(fieldName + ";")
	}
	builder.NewLine()

	// Constructor
	builder.WriteLine("constructor() {").
		Indent()
	for _, field := range model.Fields {
		fieldName := cclUtils.ToCamelCase(field.Name)
		defaultValue := "null"
		if field.IsArray() {
			defaultValue = "[]"
		} else {
			switch field.Type.GetName() {
			case cclValues.TypeNameString:
				defaultValue = "\"\""
			case cclValues.TypeNameInt, cclValues.TypeNameInt8, cclValues.TypeNameInt16, cclValues.TypeNameInt32, cclValues.TypeNameInt64,
				cclValues.TypeNameUint, cclValues.TypeNameUint8, cclValues.TypeNameUint16, cclValues.TypeNameUint32, cclValues.TypeNameUint64,
				cclValues.TypeNameFloat, cclValues.TypeNameFloat32, cclValues.TypeNameFloat64, cclValues.TypeNameDateTime:
				defaultValue = "0"
			case cclValues.TypeNameBool:
				defaultValue = "false"
			case cclValues.TypeNameBytes:
				defaultValue = "new Uint8Array(0)"
			default:
				if field.Type.IsCustomTypeModel() {
					defaultValue = "null"
				}
			}
		}

		if defaultValue != "null" {
			builder.WriteLine("this." + fieldName + " = " + defaultValue + ";")
		} else {
			builder.WriteLine("this." + fieldName + " = null;")
		}
	}
	builder.Unindent().
		WriteLine("}").
		NewLine()

	// Get Model ID
	builder.WriteLine("getModelId() {").
		Indent().
		WriteLine("return " + model.Name + "." + modelIdConstName + ";").
		Unindent().
		WriteLine("}").
		NewLine()

	// Clone Empty
	builder.WriteLine("cloneEmpty() {").
		Indent().
		WriteLine("return new " + model.Name + "();").
		Unindent().
		WriteLine("}").
		NewLine()

	builder.Unindent().
		WriteLine("}")

	return nil
}
