package jsGenerator

import (
	"os"
	"strings"

	"github.com/ALiwoto/ssg/ssg"
	"github.com/ALiwoto/ssg/ssg/caseUtils"
	gen "github.com/ccl-lang/ccl/src/cclGenerators"
	gValues "github.com/ccl-lang/ccl/src/core/globalValues"
	"github.com/ccl-lang/ccl/src/inputLangs/cclInput/cclErrors"
	"github.com/ccl-lang/ccl/src/inputLangs/cclInput/cclUtils/codeBuilder"
	"github.com/ccl-lang/ccl/src/inputLangs/cclInput/cclValues"
)

func (c *JavaScriptGenerationContext) generateCode() (*gen.CodeGenerationResult, error) {
	c.IsSingleFile, c.SingleFileName = c.IsSingleFileMode(LanguageName)

	if c.IsSingleFile {
		if c.SingleFileName == "" {
			c.SingleFileName = "generated.js"
		}

		c.SingleFileBuilder = codeBuilder.NewCodeBuilderWithOptions(&codeBuilder.CodeBuilderOptions{
			IndentationStr:  "\t",
			NewLineStr:      "\n",
			EnableDebugInfo: c.Options.GenerateDebugInfo,
		})
		c.SingleFileBuilder.BeginSection(codeBuilder.SectionCommentHeaders)
		c.SingleFileBuilder.AddCommentHeader("// THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.")
		c.SingleFileBuilder.EndSection()
	}

	// Generate each model class
	for _, typeDef := range c.GetGenerationTypeDefinitions() {
		if typeDef.IsCustomModel() {
			err := c.generateCodeForModel(typeDef.GetModelDefinition())
			if err != nil {
				return nil, err
			}
		} else if typeDef.IsCustomEnum() {
			enumDef := typeDef.GetEnumDefinition()
			if enumDef.IsNested() {
				continue
			}
			if err := c.generateCodeForEnum(enumDef); err != nil {
				return nil, err
			}
		} else {
			return nil, &cclErrors.UnsupportedTypeDefinitionError{
				TypeName:       typeDef.GetFullName(),
				TargetLanguage: LanguageName.String(),
			}
		}
	}

	result := &gen.CodeGenerationResult{
		SourceLanguage: gValues.LanguageCCL.String(),
		TargetLanguage: gValues.LanguageJS.String(),
		OutputFiles:    []string{},
	}

	if c.IsSingleFile {
		path := c.Options.OutputPath + string(os.PathSeparator) + c.SingleFileName
		err := c.WriteCodeFile(path, c.SingleFileBuilder.Build(nil))
		if err != nil {
			return nil, err
		}
		result.OutputFiles = append(result.OutputFiles, path)
	} else {
		for modelName, builder := range c.ModelClasses {
			path := c.Options.OutputPath + string(os.PathSeparator) + modelName + ".js"
			err := c.WriteCodeFile(path, builder.Build(nil))
			if err != nil {
				return nil, err
			}
			result.OutputFiles = append(result.OutputFiles, path)
		}
	}

	return result, nil
}

func (c *JavaScriptGenerationContext) generateCodeForEnum(enumDef *CCLEnum) error {
	var builder *codeBuilder.CodeBuilder
	if c.IsSingleFile {
		builder = c.SingleFileBuilder
	} else {
		builder = codeBuilder.NewCodeBuilderWithOptions(&codeBuilder.CodeBuilderOptions{
			IndentationStr:  "\t",
			NewLineStr:      "\n",
			EnableDebugInfo: c.Options.GenerateDebugInfo,
		})
		c.ModelClasses[enumDef.Name] = builder
	}

	builder.BeginSection(enumDef.GetFullName())
	defer builder.EndSection()

	if !c.IsSingleFile {
		builder.AddCommentHeader("// THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.")
	}

	return c.generateEnumObjectDeclaration(builder, enumDef, "export const ")
}

func (c *JavaScriptGenerationContext) generateCodeForModel(model *CCLModel) error {
	var builder *codeBuilder.CodeBuilder
	if c.IsSingleFile {
		builder = c.SingleFileBuilder
	} else {
		builder = codeBuilder.NewCodeBuilderWithOptions(&codeBuilder.CodeBuilderOptions{
			IndentationStr:  "\t",
			NewLineStr:      "\n",
			EnableDebugInfo: c.Options.GenerateDebugInfo,
		})
		c.ModelClasses[model.Name] = builder
	}

	builder.BeginSection(model.GetFullName())
	defer builder.EndSection()

	if !c.IsSingleFile {
		builder.AddCommentHeader("// THIS FILE IS AUTOGENERATED BY A CCL TOOL. DO NOT EDIT.")
	}

	// In multi-file mode, we need to import other models if they are referenced.
	if !c.IsSingleFile {
		for _, field := range model.Fields {
			targetType := field.Type
			if targetType.IsArray() {
				targetType = targetType.GetUnderlyingType()
			}
			if targetType.IsCustomTypeModel() {
				// Import the custom type
				// Assuming same directory for now
				builder.DoImport(targetType.GetName(), "import { "+targetType.GetName()+" } from './"+targetType.GetName()+".js';")
			} else if targetType.IsCustomTypeEnum() {
				enumDef := targetType.GetDefinition().GetEnumDefinition()
				if enumDef.IsNested() {
					if enumDef.OwnedBy != nil && enumDef.OwnedBy != model {
						builder.DoImport(
							enumDef.OwnedBy.Name,
							"import { "+enumDef.OwnedBy.Name+" } from './"+enumDef.OwnedBy.Name+".js';",
						)
					}
				} else {
					enumTypeName, err := c.getJavaScriptEnumTypeName(enumDef)
					if err != nil {
						return err
					}
					builder.DoImport(enumDef.GetFullName(), "import { "+enumTypeName+" } from './"+enumDef.Name+".js';")
				}
			}
		}
	}

	err := c.generateModelClass(builder, model)
	if err != nil {
		return err
	}

	return nil
}

func (c *JavaScriptGenerationContext) generateModelClass(builder *codeBuilder.CodeBuilder, model *CCLModel) error {
	modelIdConstName := "MODEL_ID_" + strings.ToUpper(caseUtils.ToSnakeCase(model.Name))
	builder.MapVarPairs(
		"model", model.Name,
		"modelIdConst", modelIdConstName,
		"modelId", ssg.ToBase10(model.ModelId),
	)
	defer builder.UnmapVar(
		"model",
		"modelIdConst",
		"modelId",
	)

	builder.LineD("export class $model {").
		Indent()

	for _, enumDef := range model.Enums {
		if err := c.generateEnumObjectDeclaration(builder, enumDef, "static "); err != nil {
			return err
		}
		builder.NewLine()
	}

	// Write model ID constant
	builder.LineD("static $modelIdConst = $modelId;").
		NewLine()

	// Fields
	for _, field := range model.Fields {
		fieldName := caseUtils.ToCamelCase(field.Name)
		builder.MapVarPairs(
			"field", fieldName,
		)
		builder.LineD("$field;")
		builder.UnmapVar("field")
	}
	builder.NewLine()

	// Constructor
	builder.WriteLine("constructor() {").
		Indent()
	for _, field := range model.Fields {
		fieldName := caseUtils.ToCamelCase(field.Name)
		defaultValue := "null"
		if field.IsArray() {
			defaultValue = "[]"
		} else if field.HasDefaultValue() {
			defaultValue = javaScriptDefaultLiteral(field.GetDefaultValue())
			if enumRef := c.GetEnumDefaultReference(field); enumRef != nil {
				ref, err := c.getJavaScriptEnumReference(enumRef.Enum, enumRef.Member)
				if err != nil {
					return err
				}
				defaultValue = ref
			}
		} else {
			switch field.Type.GetName() {
			case cclValues.TypeNameString:
				defaultValue = "\"\""
			case cclValues.TypeNameInt, cclValues.TypeNameInt8, cclValues.TypeNameInt16, cclValues.TypeNameInt32, cclValues.TypeNameInt64,
				cclValues.TypeNameUint, cclValues.TypeNameUint8, cclValues.TypeNameUint16, cclValues.TypeNameUint32, cclValues.TypeNameUint64,
				cclValues.TypeNameFloat, cclValues.TypeNameFloat32, cclValues.TypeNameFloat64, cclValues.TypeNameDateTime:
				defaultValue = "0"
			case cclValues.TypeNameBool:
				defaultValue = "false"
			case cclValues.TypeNameBytes:
				defaultValue = "new Uint8Array(0)"
			default:
				if field.Type.IsCustomTypeEnum() {
					defaultValue = "0"
				} else if field.Type.IsCustomTypeModel() {
					defaultValue = "null"
				}
			}
		}

		if defaultValue != "null" {
			builder.MapVarPairs(
				"defaultValue", defaultValue,
				"field", fieldName,
			)
			builder.LineD("this.$field = $defaultValue;")
			builder.UnmapVar(
				"defaultValue",
				"field",
			)
		} else {
			builder.MapVarPairs(
				"field", fieldName,
			)
			builder.LineD("this.$field = null;")
			builder.UnmapVar("field")
		}
	}
	builder.Unindent().
		WriteLine("}").
		NewLine()

	// Get Model ID
	builder.WriteLine("getModelId() {").
		Indent().
		LineD("return $model.$modelIdConst;").
		Unindent().
		WriteLine("}").
		NewLine()

	if c.NeedsCloneMethods(LanguageName, model) {
		if err := c.generateCloneMethods(model, builder); err != nil {
			return err
		}
	}

	if c.NeedsJsonSerialization(LanguageName, model) {
		if err := c.generateSerializeJsonMethods(model, builder); err != nil {
			return err
		}
	}

	builder.Unindent().
		WriteLine("}")

	return nil
}
