name: tests-windows

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Set up Godot
      uses: chickensoft-games/setup-godot@v2
      with:
        version: 4.5.0

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '22'

    - name: Test
      run: go test -v ./...