name: tests-macos

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:

  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v5
    - uses: ./.github/actions/ccl-tests-deps

    - name: Test
      run: go test -v ./...
